- platform: template
  sensors:
    people_home:
      friendly_name: People Home
      device_class: presence
      value_template: >
        {{ is_state('person.sen', 'home') or
        is_state('person.kris', 'home') }}

# Check if any window is open
- platform: group
  name: Windows
  device_class: window
  entities:
    - binary_sensor.bedroom_window_contact
    - binary_sensor.kitchen_window_contact
    - binary_sensor.living_room_window_contact

# ADS-B System / Flightradar 24
- platform: template
  sensors:
    fr24_feeder_receiver_connected:
      friendly_name: Receiver Connected
      value_template: '{{ is_state_attr("sensor.fr24_feeder", "rx_connected", "1") }}'
      device_class: connectivity
    fr24_feeder_link_connected:
      friendly_name: Link Connected
      value_template: '{{ is_state_attr("sensor.fr24_feeder", "feed_status", "connected") }}'
      device_class: connectivity

- platform: trend
  sensors:
    diesel_price_ono_trend:
      friendly_name: "Diesel Price ONO Trend"
      entity_id: sensor.diesel_price_ono
      min_samples: 1