###############################################
## Gas Meter Sensor from Gas Counter
###############################################
- platform: template
  sensors:
    gas_meter:
      friendly_name: Gas Meter
      value_template: "{{ states ('counter.gas_counter') | float * 0.01}}"
      unit_of_measurement: "m³"
      icon_template: "mdi:fire"
      device_class: gas

###############################################
## Distance Between Persons Sensor in Meters
###############################################
- platform: template
  sensors:
    distance_between_kris_and_sen:
      friendly_name: Distance Between Kris and Sen
      value_template: "{{ (distance(states.person.sen, states.person.kris) * 1000) | round(0) }}"
      unit_of_measurement: "m"
      icon_template: "mdi:map-marker-distance"

###############################################
## UPS Power Sensor
###############################################
- platform: template
  sensors:
    ups_power:
      friendly_name: UPS Power
      value_template: "{{ states('sensor.ups_load') | int  * 0.01 * 425 | round(2) }}"
      unit_of_measurement: "W"
      icon_template: "mdi:gauge"
      device_class: power

###############################################
## System Monitor Sensors
###############################################
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: processor_temperature
    - type: last_boot
    - type: disk_use_percent
    - type: disk_use
    - type: memory_use_percent
    - type: swap_use_percent
    - type: load_1m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0

###############################################
## Other Sensors
###############################################
- platform: time_date
  display_options:
    - "time"
    - "date"

###############################################
## Last Changed Sensors
###############################################
- platform: template
  sensors:
    hall_last_motion:
      friendly_name: "Hall Last Motion"
      value_template: >
        {{ as_timestamp(states.binary_sensor.tradfri_motion_sensor_occupancy.last_changed) | timestamp_custom('%d.%m.%Y %H:%M:%S',1) }}
    front_door_last_triggered:
      friendly_name: "Front Door Last Triggered"
      value_template: >
        {{ as_timestamp(states.binary_sensor.aqara_hall_door_sensor_contact.last_changed) | timestamp_custom('%d.%m.%Y %H:%M:%S',1) }}
    bedroom_window_last_triggered:
      friendly_name: "Bedroom Window Last Triggered"
      value_template: >
        {{ as_timestamp(states.binary_sensor.aqara_bedroom_window_sensor_contact.last_changed) | timestamp_custom('%d.%m.%Y %H:%M:%S',1) }}
    bedroom_door_last_triggered:
      friendly_name: "Bedroom Door Last Triggered"
      value_template: >
        {{ as_timestamp(states.binary_sensor.aqara_bedroom_door_sensor_contact.last_changed) | timestamp_custom('%d.%m.%Y %H:%M:%S',1) }}
    raven_last_message_received:
      friendly_name: "Raven Last Message Received"
      value_template: >
        {{ as_timestamp(states.sensor.raven_rssi.last_changed) | timestamp_custom('%d.%m.%Y %H:%M:%S',1) }}

###############################################
## Solar Station Sensors
###############################################
- platform: template
  sensors:
    solar_energy_production_today:
      friendly_name: "Solar Energy Production Today"
      value_template: >
        {{ (float(states('sensor.solar_panel_energy')) -
        float(states('input_number.solar_energy_produced_at_beginning_of_day'))) | round(3) }}
      unit_of_measurement: "Wh"
      device_class: energy

###############################################
## DuinoCoin Statistics Sensors
###############################################
- platform: statistics
  name: "Duco Mined over 5 minutes"
  entity_id: sensor.duco_balance
  state_characteristic: change
  max_age:
    minutes: 5
  sampling_size: 10
  precision: 5

- platform: statistics
  name: "Duco Mined over 1 hour"
  entity_id: sensor.duco_balance
  state_characteristic: change
  max_age:
    hours: 1
  sampling_size: 70
  precision: 5

- platform: statistics
  name: "Duco Mined over 1 day"
  entity_id: sensor.duco_balance
  state_characteristic: change
  max_age:
    days: 1
  sampling_size: 1500
  precision: 5
