###############################################
## Distance Between Persons Sensor in Meters
###############################################
- platform: template
  sensors:
    distance_between_kris_and_sen:
      friendly_name: Distance Between Kris and Sen
      value_template: "{{ (distance(states.person.sen, states.person.kris) * 1000) | round(0, default=none) }}"
      unit_of_measurement: "m"
      icon_template: "mdi:map-marker-distance"

###############################################
## Other Sensors
###############################################
- platform: time_date
  display_options:
    - "time"
    - "date"

###############################################
## Last Changed Sensors
###############################################
- platform: template
  sensors:
    front_door_last_triggered:
      friendly_name: "Front Door Last Triggered"
      value_template: >
        {{ as_timestamp(states.binary_sensor.hall_door_contact.last_changed, 0) | timestamp_custom('%d.%m.%Y %H:%M:%S',1) }}
    bedroom_window_last_triggered:
      friendly_name: "Bedroom Window Last Triggered"
      value_template: >
        {{ as_timestamp(states.binary_sensor.bedroom_window_contact.last_changed, 0) | timestamp_custom('%d.%m.%Y %H:%M:%S',1) }}
    bedroom_door_last_triggered:
      friendly_name: "Bedroom Door Last Triggered"
      value_template: >
        {{ as_timestamp(states.binary_sensor.bedroom_door_contact.last_changed, 0) | timestamp_custom('%d.%m.%Y %H:%M:%S',1) }}

###############################################
## Energy Sensors
###############################################
- platform: template
  sensors:
    grid_consumed_today_cost:
      friendly_name: "Grid Consumed Today Cost"
      value_template: >
        {{ ((states('sensor.grid_consumed_today') | float(0.0)) * 10) | round(2, default=0) }}
      unit_of_measurement: "Kč"
      device_class: monetary

###############################################
## ADS-B System / Flightradar 24
###############################################
- platform: rest
  name: FR24 Feeder
  resource: http://127.0.0.1:8754/monitor.json
  value_template: "{{ value_json.feed_alias }}"
  method: GET
  scan_interval: 60
  json_attributes:
    - rx_connected
    - feed_status
    - d11_map_size
    - feed_num_ac_tracked
    - build_version
    - feed_alias
- platform: template
  sensors:
    fr24_feeder_radar_code:
      friendly_name: Radar Code
      value_template: "{{ state_attr('sensor.fr24_feeder', 'feed_alias') }}"
    fr24_feeder_aircraft_tracked:
      friendly_name: Aircraft Tracked
      value_template: "{{ state_attr('sensor.fr24_feeder', 'd11_map_size') | round(0, default=none) }}"
      unit_of_measurement: "aircrafts"
    fr24_feeder_aircraft_uploaded:
      friendly_name: Aircraft Uploaded
      value_template: "{{ state_attr('sensor.fr24_feeder', 'feed_num_ac_tracked') | round(0, default=none) }}"
      unit_of_measurement: "aircrafts"
    fr24_feeder_version:
      friendly_name: Version
      value_template: "{{ state_attr('sensor.fr24_feeder', 'build_version') }}"

- platform: rest
  name: FR24 Aircraft
  resource: http://127.0.0.1:8080/data/aircraft.json
  value_template: "{{ value_json.messages }}"
  method: GET
  scan_interval: 15
  json_attributes:
    - now
    - aircraft

- platform: template
  sensors:
    mikrotik_wireless_clients:
      friendly_name: "Mikrotik Clients"
      value_template: "{{ states('sensor.mikrotik_hap_ax_3_wireless_clients') | int(0) }}"
      unit_of_measurement: "clients"

###############################################
## History Stats
###############################################
- platform: history_stats
  name: Heating Today
  entity_id: binary_sensor.thermostat_heating
  state: "on"
  type: time
  start: "{{ today_at('00:00:00') }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Heating Yesterday
  entity_id: binary_sensor.thermostat_heating
  state: "on"
  type: time
  end: "{{ today_at('00:00:00') }}"
  duration:
    days: 1
- platform: history_stats
  name: Heating Bedroom Today
  entity_id: binary_sensor.heating_request_bedroom
  state: "on"
  type: time
  start: "{{ today_at('00:00:00') }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Heating Bedroom Yesterday
  entity_id: binary_sensor.heating_request_bedroom
  state: "on"
  type: time
  end: "{{ today_at('00:00:00') }}"
  duration:
    days: 1
- platform: history_stats
  name: Heating Kitchen Today
  entity_id: binary_sensor.heating_request_kitchen
  state: "on"
  type: time
  start: "{{ today_at('00:00:00') }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Heating Kitchen Yesterday
  entity_id: binary_sensor.heating_request_kitchen
  state: "on"
  type: time
  end: "{{ today_at('00:00:00') }}"
  duration:
    days: 1
- platform: history_stats
  name: Heating Living Room Today
  entity_id: binary_sensor.heating_request_living_room
  state: "on"
  type: time
  start: "{{ today_at('00:00:00') }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Heating Living Room Yesterday
  entity_id: binary_sensor.heating_request_living_room
  state: "on"
  type: time
  end: "{{ today_at('00:00:00') }}"
  duration:
    days: 1
