###############################################
## Gas Meter Sensor from Gas Counter
###############################################
- platform: template
  sensors:
    gas_meter:
      friendly_name: Gas Meter
      value_template: "{{ states ('counter.gas_counter') | float * 0.01}}"
      unit_of_measurement: "m³"
      icon_template: "mdi:fire"
      device_class: gas

###############################################
## Distance Between Persons Sensor in Meters
###############################################
- platform: template
  sensors:
    distance_between_kris_and_sen:
      friendly_name: Distance Between Kris and Sen
      value_template: "{{ (distance(states.person.sen, states.person.kris) * 1000) | round(0) }}"
      unit_of_measurement: "m"
      icon_template: "mdi:map-marker-distance"

###############################################
## System Monitor Sensors
###############################################
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: processor_temperature
    - type: last_boot
    - type: disk_use_percent
    - type: disk_use
    - type: memory_use_percent
    - type: swap_use_percent
    - type: load_1m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0

###############################################
## Other Sensors
###############################################
- platform: time_date
  display_options:
    - "time"
    - "date"

###############################################
## Last Changed Sensors
###############################################
- platform: template
  sensors:
    front_door_last_triggered:
      friendly_name: "Front Door Last Triggered"
      value_template: >
        {{ as_timestamp(states.binary_sensor.hall_door_contact.last_changed) | timestamp_custom('%d.%m.%Y %H:%M:%S',1) }}
    bedroom_window_last_triggered:
      friendly_name: "Bedroom Window Last Triggered"
      value_template: >
        {{ as_timestamp(states.binary_sensor.bedroom_window_contact.last_changed) | timestamp_custom('%d.%m.%Y %H:%M:%S',1) }}
    bedroom_door_last_triggered:
      friendly_name: "Bedroom Door Last Triggered"
      value_template: >
        {{ as_timestamp(states.binary_sensor.bedroom_door_contact.last_changed) | timestamp_custom('%d.%m.%Y %H:%M:%S',1) }}
    raven_last_message_received:
      friendly_name: "Raven Last Message Received"
      value_template: >
        {{ as_timestamp(states.sensor.raven_rssi.last_changed) | timestamp_custom('%d.%m.%Y %H:%M:%S',1) }}

###############################################
## Solar Station Sensors
###############################################
- platform: template
  sensors:
    solar_energy_production_today:
      friendly_name: "Solar Energy Production Today"
      value_template: >
        {{ (float(states('sensor.solar_panel_energy')) -
        float(states('input_number.solar_energy_produced_at_beginning_of_day'))) | round(3) }}
      unit_of_measurement: "Wh"
      device_class: energy

###############################################
## Energy Sensors
###############################################
- platform: template
  sensors:
    energy_consumed_today_cost:
      friendly_name: "Energy Consumed Today Cost"
      value_template: >
        {{ ((states('sensor.electricity_meter_energy') | float(0.0) -
        (states('input_number.energy_consumed_at_beginning_of_day') | float(0.0))) * 10) | round(2) }}
      unit_of_measurement: "Kč"
      device_class: monetary

###############################################
## ADS-B System / Flightradar 24
###############################################
- platform: rest
  name: FR24 Feeder
  resource: http://127.0.0.1:8754/monitor.json
  value_template: "{{ value_json.feed_alias }}"
  method: GET
  scan_interval: 60
  json_attributes:
    - rx_connected
    - feed_status
    - d11_map_size
    - feed_num_ac_tracked
    - build_version
    - feed_alias
- platform: template
  sensors:
    fr24_feeder_radar_code:
      friendly_name: Radar Code
      value_template: '{{ states.sensor.fr24_feeder.attributes["feed_alias"] }}'
    fr24_feeder_aircraft_tracked:
      friendly_name: Aircraft Tracked
      value_template: '{{ states.sensor.fr24_feeder.attributes["d11_map_size"] | round(0) }}'
      unit_of_measurement: "aircrafts"
    fr24_feeder_aircraft_uploaded:
      friendly_name: Aircraft Uploaded
      value_template: '{{ states.sensor.fr24_feeder.attributes["feed_num_ac_tracked"] | round(0) }}'
      unit_of_measurement: "aircrafts"
    fr24_feeder_version:
      friendly_name: Version
      value_template: '{{ states.sensor.fr24_feeder.attributes["build_version"] }}'

- platform: rest
  name: FR24 Aircraft
  resource: http://127.0.0.1:8080/data/aircraft.json
  value_template: "{{ value_json.messages }}"
  method: GET
  scan_interval: 15
  json_attributes:
    - now
    - aircraft

- platform: template
  sensors:
    mikrotik_wireless_clients:
      friendly_name: "Mikrotik Clients"
      value_template: "{{ states('sensor.mikrotik_hap_ax_3_wireless_clients') | int }}"
      unit_of_measurement: "clients"
