###############################################
## Water Quality Rest Sensors
###############################################

resource: !secret WATER_QUALITY_URI
scan_interval: 3600
sensor:
  # Actual values
  - name: "Water Quality Color"
    value_template: "{{ value_json['Barva']['value'] }}"
    unit_of_measurement: "mg Pt/l"
  - name: "Water Quality Turbidity"
    value_template: "{{ value_json['Zákal']['value'] }}"
    unit_of_measurement: "NTU"
  - name: "Water Quality Iron"
    value_template: "{{ value_json['Železo']['value'] }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality pH"
    value_template: "{{ value_json['pH']['value'] }}"
    unit_of_measurement: "pH"
  - name: "Water Quality Hardness"
    value_template: "{{ value_json['Tvrdost']['value'] }}"
    unit_of_measurement: "mmol/l"
  - name: "Water Quality Ammonium Ions"
    value_template: "{{ value_json['Amonné ionty']['value'] }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality Nitrates"
    value_template: "{{ value_json['Dusičnany']['value'] }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality Nitrites"
    value_template: "{{ value_json['Dusitany']['value'] }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality Chlorides"
    value_template: "{{ value_json['Chloridy']['value'] }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality TOC" # Total Organic Carbon
    value_template: "{{ value_json['TOC']['value'] }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality Free Chlorine"
    value_template: "{{ value_json['Volný chlor']['value'] }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality Coliform Bacteria"
    value_template: "{{ value_json['Koliformní b.']['value'] }}"
    unit_of_measurement: "KTJ/100ml"
  - name: "Water Quality Escherichia coli"
    value_template: "{{ value_json['E. coli']['value'] }}"
    unit_of_measurement: "KTJ/100ml"

  # Limits
  - name: "Water Quality Color Limit"
    value_template: "{{ value_json['Barva']['limit'] }}"
    unit_of_measurement: "{{ value_json['Barva']['unit'] }}"
  - name: "Water Quality Turbidity Limit"
    value_template: "{{ value_json['Zákal']['limit'] }}"
    unit_of_measurement: "{{ value_json['Zákal']['unit'] }}"
  - name: "Water Quality Iron Limit"
    value_template: "{{ value_json['Železo']['limit'] }}"
    unit_of_measurement: "{{ value_json['Železo']['unit'] }}"
  - name: "Water Quality pH Limit"
    value_template: "{{ value_json['pH']['limit'] }}"
    unit_of_measurement: "{{ value_json['pH']['unit'] }}"
  - name: "Water Quality Hardness Limit"
    value_template: "{{ value_json['Tvrdost']['limit'] }}"
    unit_of_measurement: "{{ value_json['Tvrdost']['unit'] }}"
  - name: "Water Quality Ammonium Ions Limit"
    value_template: "{{ value_json['Amonné ionty']['limit'] }}"
    unit_of_measurement: "{{ value_json['Amonné ionty']['unit'] }}"
  - name: "Water Quality Nitrates Limit"
    value_template: "{{ value_json['Dusičnany']['limit'] }}"
    unit_of_measurement: "{{ value_json['Dusičnany']['unit'] }}"
  - name: "Water Quality Nitrites Limit"
    value_template: "{{ value_json['Dusitany']['limit'] }}"
    unit_of_measurement: "{{ value_json['Dusitany']['unit'] }}"
  - name: "Water Quality Chlorides Limit"
    value_template: "{{ value_json['Chloridy']['limit'] }}"
    unit_of_measurement: "{{ value_json['Chloridy']['unit'] }}"
  - name: "Water Quality TOC Limit" # Total Organic Carbon
    value_template: "{{ value_json['TOC']['limit'] }}"
    unit_of_measurement: "{{ value_json['TOC']['unit'] }}"
  - name: "Water Quality Free Chlorine Limit"
    value_template: "{{ value_json['Volný chlor']['limit'] }}"
    unit_of_measurement: "{{ value_json['Volný chlor']['unit'] }}"
  - name: "Water Quality Coliform Bacteria Limit"
    value_template: "{{ value_json['Koliformní b.']['limit'] }}"
    unit_of_measurement: "{{ value_json['Koliformní b.']['unit'] }}"
  - name: "Water Quality Escherichia coli Limit"
    value_template: "{{ value_json['E. coli']['limit'] }}"
    unit_of_measurement: "{{ value_json['E. coli']['unit'] }}"
