###############################################
## Water Quality Rest Sensors
###############################################

resource: !secret WATER_QUALITY_URI
scan_interval: 3600
sensor:
  # Actual values
  - name: "Water Quality Color"
    value_template: "{{ value_json['Barva']['value'] | replace(',','.') | replace('<','')   }}"
    unit_of_measurement: "mg Pt/l"
  - name: "Water Quality Turbidity"
    value_template: "{{ value_json['Zákal']['value'] | replace(',','.') | replace('<','')    }}"
    unit_of_measurement: "NTU"
  - name: "Water Quality Iron"
    value_template: "{{ value_json['Železo']['value'] | replace(',','.') | replace('<','')    }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality pH"
    value_template: "{{ value_json['pH']['value'] | replace(',','.') | replace('<','')    }}"
    unit_of_measurement: "pH"
  - name: "Water Quality Hardness"
    value_template: "{{ value_json['Tvrdost']['value'] | replace(',','.') | replace('<','')    }}"
    unit_of_measurement: "mmol/l"
  - name: "Water Quality Ammonium Ions"
    value_template: "{{ value_json['Amonné ionty']['value'] | replace(',','.') | replace('<','')    }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality Nitrates"
    value_template: "{{ value_json['Dusičnany']['value'] | replace(',','.') | replace('<','')    }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality Nitrites"
    value_template: "{{ value_json['Dusitany']['value'] | replace(',','.') | replace('<','')    }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality Chlorides"
    value_template: "{{ value_json['Chloridy']['value'] | replace(',','.') | replace('<','')    }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality TOC" # Total Organic Carbon
    value_template: "{{ value_json['TOC']['value'] | replace(',','.') | replace('<','')    }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality Free Chlorine"
    value_template: "{{ value_json['Volný chlor']['value'] | replace(',','.') | replace('<','')    }}"
    unit_of_measurement: "mg/l"
  - name: "Water Quality Coliform Bacteria"
    value_template: "{{ value_json['Koliformní b.']['value'] | replace(',','.') | replace('<','')    }}"
    unit_of_measurement: "KTJ/100ml"
  - name: "Water Quality Escherichia coli"
    value_template: "{{ value_json['E. coli']['value'] | replace(',','.') | replace('<','')    }}"
    unit_of_measurement: "KTJ/100ml"