######################################################################
# File: 3d-printer.yaml                                              #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2023-02-19                                                   #
#                                                                    #
# Info: this file contains automations that are associated to the    #
# 3D printer connected via Octoprint                                 #
#                                                                    #
# Copyright (c) 2023 Sen Morgan                                      #
######################################################################

###############################################
## Remind me when the print is done
###############################################
- alias: "3D Printer - Print Done"
  id: "3d-printer-print-done"
  trigger:
    platform: state
    entity_id: binary_sensor.octoprint_printing
    from: "on"
    to: "off"
  action:
    - service: notify.mobile_app_sm_s901b
      data:
        title: "3D Printer"
        message: "🎉 Печать завершена!"

###############################################
## Remind me every 10% of the print
###############################################
- alias: "3D Printer - Print Progress"
  id: "3d-printer-print-progress"
  trigger:
    platform: state
    entity_id: sensor.octoprint_job_percentage
  condition:
    condition: template
    value_template: >
      {{ (trigger.to_state.state | int) > 0 and
        ((trigger.to_state.state | int) != (trigger.from_state.state | int)) and
         (trigger.to_state.state | int) % 10 == 0 }}
  action:
    - service: notify.mobile_app_sm_s901b
      data_template:
        title: "3D Printer"
        message: "📈 Деталь готова на {{ states('sensor.octoprint_job_percentage') | int }}%"

###############################################
## Remind me when print is paused
###############################################
- alias: "3D Printer - Print Paused"
  id: "3d-printer-print-paused"
  trigger:
    platform: state
    entity_id: sensor.octoprint_current_state
    from: "Printing"
    to:
      - "Paused"
      - "Pausing"
  action:
    - service: notify.mobile_app_sm_s901b
      data:
        title: "⚠️ 3D Printer"
        message: "Печать приостановлена!"

###############################################
## Remind me when print is resumed
###############################################
- alias: "3D Printer - Print Resumed"
  id: "3d-printer-print-resumed"
  trigger:
    platform: state
    entity_id: sensor.octoprint_current_state
    from:
      - "Paused"
      - "Pausing"
    to: "Printing"
  action:
    - service: notify.mobile_app_sm_s901b
      data:
        title: "⚠️ 3D Printer"
        message: "Печать возобновлена"

###############################################
## Remind me when bed or hotend is overheated
###############################################
- alias: "3D Printer - Overheated"
  id: "3d-printer-overheated"
  trigger:
    platform: state
    entity_id:
      - sensor.octoprint_actual_bed_temp
      - sensor.octoprint_actual_tool0_temp
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: >
          {{ states('sensor.octoprint_actual_bed_temp') | int > 100 }}
      - condition: template
        value_template: >
          {{ states('sensor.octoprint_actual_tool0_temp') | int > 250 }}
  action:
    - service: notify.mobile_app_sm_s901b
      data:
        title: "🌡️ 3D Printer перегрелся!"
        message: |
          🛏️ Температура стола: {{ states('sensor.octoprint_actual_bed_temp') }}°C
          🔥 Температура хотенда: {{ states('sensor.octoprint_actual_tool0_temp') }}°C

###############################################
## Power control
###############################################
- alias: 3D Printer - Power On
  id: 3d-printer-power-on
  trigger:
    - platform: state
      entity_id: input_button.3d_printer_power_on
  action:
    - service: switch.turn_on
      entity_id: switch.3d_printer_socket

- alias: 3D Printer - Power Off
  id: 3d-printer-power-off
  trigger:
    - platform: state
      entity_id: input_button.3d_printer_power_off
  action:
    - service: script.turn_on
      entity_id: script.octoprint_shutdown
    # Wait until server is down
    - wait_template: "{{ states('sensor.octoprint_current_state') == 'unavailable' }}"
      timeout: "00:03:00"
      # If server is still up — send me notification
    - if:
        - condition: template
          value_template: "{{ states('sensor.octoprint_current_state') != 'unavailable' }}"
      then:
        - service: notify.mobile_app_sm_s901b
          data:
            title: "⚠️ 3D Printer"
            message: |
              Не удалось выключить Octoprint сервер.
              Питания НЕ отключено!
      else:
        # If server is down, turn off power socket
        - service: switch.turn_off
          entity_id: switch.3d_printer_socket
