######################################################################
# File: air_quality.yaml                                             #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2023-06-10                                                   #
#                                                                    #                                                                    #
# Copyright (c) 2023 Sen Morgan                                      #
######################################################################

###############################################
## INPUT DATETIMES
###############################################
input_datetime:
  air_quality_open_window_greeting_timeout:
    name: "Air Quality Open Window Greeting Timout"
    has_date: true
    has_time: true

###############################################
## AUTOMATIONS
###############################################
automation:
  - alias: Notification Air Quality Bad
    id: "notification_air_quality_bad"
    triggers:
      - trigger: numeric_state
        entity_id: sensor.air_quality_station_iaq
        above: 200
        for: 00:02:00
    conditions:
      - condition: state
        entity_id: input_boolean.home_night_mode
        state: "off"
    actions:
      # Check if yandex station is not playing now
      - if:
          - condition: template
            value_template: "{{ not is_state('media_player.yandex_station_midi', 'playing') }}"
        then:
          - action: media_player.play_media
            entity_id: media_player.yandex_station_midi
            data:
              # If some of windows are opened, notify to close exact opened window by telling it's name.
              # Otherwise, notify to open window.
              media_content_type: text
              media_content_id: |
                Замечено плохое качество воздуха в доме,
                {% if states('binary_sensor.windows') == 'off' %}
                  советую открыть окно.
                {% else %}
                  советую закрыть окно
                  {% if states('binary_sensor.bedroom_window_contact') == 'on' %}
                    в спальне
                  {% endif %}
                  {% if states('binary_sensor.kitchen_window_contact') == 'on' %}
                    {% if states('binary_sensor.bedroom_window_contact') == 'on' %}
                      {% if states('binary_sensor.living_room_window_contact') == 'on' %}
                        ,
                      {% else %}
                        и
                      {% endif %}
                    {% endif %}
                    на кухне
                  {% endif %}
                  {% if states('binary_sensor.living_room_window_contact') == 'on' %}
                    {% if states('binary_sensor.bedroom_window_contact') == 'on' or states('binary_sensor.kitchen_window_contact') == 'on' %}
                      и
                    {% endif %}
                    в гостинной.
                  {% endif %}
                {% endif %}
      - action: notify.mobile_app_sm_s901b
        data:
          title: "🌬 Качество воздуха"
          message: >
            Качество воздуха в доме ухудшилось и составляет {{ states('sensor.air_quality_station_iaq') }}.
      - action: automation.turn_on
        entity_id:
          - automation.notification_air_quality_restored
          - automation.notification_air_quality_open_window_greeting
      # Set timeout for open window greeting notification
      - action: input_datetime.set_datetime
        data:
          entity_id: input_datetime.air_quality_open_window_greeting_timeout
          datetime: "{{ now() + timedelta(minutes=2) }}"
      # Disable bad air quality notification till it will be restored
      - action: automation.turn_off
        entity_id: automation.notification_air_quality_bad

  - alias: Notification Air Quality Open Window Greeting
    id: "notification_air_quality_open_window_greeting"
    triggers:
      - trigger: state
        entity_id: binary_sensor.windows
        from: "off"
        to: "on"
    conditions:
      - condition: state
        entity_id: input_boolean.home_night_mode
        state: "off"
    actions:
      - if:
          # Check if timeout for open window greeting notification has not expired
          - condition: template
            value_template: "{{ as_timestamp(now()) < as_timestamp(states('input_datetime.air_quality_open_window_greeting_timeout'), 0) }}"
          # Check if yandex station is not playing now
          - condition: template
            value_template: "{{ not is_state('media_player.yandex_station_midi', 'playing') }}"
        then:
          - action: media_player.play_media
            entity_id: media_player.yandex_station_midi
            data:
              media_content_type: text
              media_content_id: Молодец! Рада, что вы заботитесь о своём здоровье.
      - action: automation.turn_off
        entity_id: automation.notification_air_quality_open_window_greeting

  - alias: Notification Air Quality Restored
    id: "notification_air_quality_restored"
    triggers:
      - trigger: numeric_state
        entity_id: sensor.air_quality_station_iaq
        below: 50
        for: 00:02:00
    conditions:
      - condition: state
        entity_id: input_boolean.home_night_mode
        state: "off"
    actions:
      # Check if yandex station is not playing now
      - if:
          - condition: template
            value_template: "{{ not is_state('media_player.yandex_station_midi', 'playing') }}"
        then:
          - action: media_player.play_media
            entity_id: media_player.yandex_station_midi
            data:
              media_content_type: text
              media_content_id: Качество воздуха в доме вернулось в норму.
      - action: notify.mobile_app_sm_s901b
        data:
          title: "🌬 Качество воздуха"
          message: >
            Качество воздуха в доме улучшилось и составляет {{ states('sensor.air_quality_station_iaq') }}.
      - action: automation.turn_on
        entity_id: automation.notification_air_quality_bad
      - action: automation.turn_off
        entity_id:
          - automation.notification_air_quality_restored
          - automation.notification_air_quality_open_window_greeting
