######################################################################
# File: dcc_ex.yaml                                                  #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2024-01-21                                                   #
#                                                                    #
# Info: this file contains entities that are associated to the       #
# DCC-EX protocol and my model railway layout.                       #
# More info about DCC-EX API:                                        #
# https://dcc-ex.com/reference/developers/api.html#gsc.tab=0         #
#                                                                    #
# Copyright (c) 2024 Sen Morgan                                      #
######################################################################

###############################################
## SETTINGS AND VARIABLES
###############################################
homeassistant:
  customize:
    package.node_anchors:
      defaults: &defaults
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        timeout: &telnet_cmd_timeout 0.2

###############################################
## CUSTOMIZATIONS
###############################################
    switch.dcc_ex_pwr:
        icon: mdi:power
    switch.dcc_ex_pause:
        icon: mdi:play-pause
    switch.dcc_ex_vossloh_engine:
        icon: mdi:engine-outline
    switch.dcc_ex_vossloh_horn:
        icon: mdi:bullhorn-outline
    switch.dcc_ex_vossloh_cabin_lights:
        icon: mdi:light-flood-down
    switch.dcc_ex_cargo_power_sound:
      icon: mdi:transmission-tower
    switch.dcc_ex_cargo_cab_start_up:
      icon: mdi:car-cog
    switch.dcc_ex_cargo_general_station_sounds:
      icon: mdi:bullhorn-outline
    switch.dcc_ex_cargo_inspection_lights:
      icon: mdi:light-flood-down

###############################################
## INPUT BUTTONS
###############################################
input_button:
  dcc_ex_emergency_stop:
    name: "DCC-EX Emergency Stop"
    icon: mdi:alert
  dcc_ex_reboot:
    name: "DCC-EX Reboot"
    icon: mdi:restart
  dcc_ex_route_300:
    name: "DCC-EX Route 300"
    icon: mdi:railroad-light
  dcc_ex_route_301:
    name: "DCC-EX Route 301"
    icon: mdi:railroad-light

###############################################
## LIGHTS
###############################################
light:
  - platform: switch
    name: "Model Railway Lights"
    entity_id: switch.dcc_ex_pwr

###############################################
## SHELL COMMANDS
###############################################
shell_command:
  dcc_ex_command: >-
    /config/scripts/dcc_ex_command.sh
    -c '{{ command_type }}'
    -v '{{ command_value }}'
    -a '{{ dcc_ex_server_ip }}'
    -p '{{ dcc_ex_server_port }}'

###############################################
## MEDIA PLAYER - Used for easier control of volume, power, etc.
###############################################
media_player:
  - platform: universal
    name: "Model Railway"
    commands:
      turn_on:
        action: switch.turn_on
        entity_id: switch.dcc_ex_pwr
      turn_off:
        action: switch.turn_off
        entity_id: switch.dcc_ex_pwr
      volume_up:
        service: shell_command.dcc_ex_command
        data:
          command_type: "volume"
          command_value: "64"
          dcc_ex_server_ip: !secret DCC-EX-SERVER-IP
          dcc_ex_server_port: !secret DCC-EX-SERVER-PORT
      volume_down:
        service: shell_command.dcc_ex_command
        data:
          command_type: "volume"
          command_value: "20"
          dcc_ex_server_ip: !secret DCC-EX-SERVER-IP
          dcc_ex_server_port: !secret DCC-EX-SERVER-PORT
      volume_set:
        service: shell_command.dcc_ex_command
        data:
          command_type: "volume"
          command_value: "{{ volume_level }}"
          dcc_ex_server_ip: !secret DCC-EX-SERVER-IP
          dcc_ex_server_port: !secret DCC-EX-SERVER-PORT
      volume_mute:
        service: shell_command.dcc_ex_command
        data:
          command_type: "volume"
          command_value: "0"
          dcc_ex_server_ip: !secret DCC-EX-SERVER-IP
          dcc_ex_server_port: !secret DCC-EX-SERVER-PORT
      media_play:
        action: switch.turn_on
        entity_id: input_button.dcc_ex_pause
      media_pause:
        action: switch.turn_off
        entity_id: input_button.dcc_ex_pause
    attributes:
      state: switch.dcc_ex_pwr
    device_class: speaker

###############################################
## SWITCHES
###############################################
switch:
  - platform: telnet
    switches:
      ###############################################
      ## Common DCC-EX Commands
      ###############################################
      dcc_ex_pwr:
        <<: *defaults
        name: "DCC-EX Power and Loco Lights"
        # Power all tracks, enable loco's lights (main + cab), set max volume on both locos
        command_on: "<1> <F 4 0 1> <F 4 15 1> <W 4 63 64> <F 5 0 1> <W 5 158 64>"
        # Power off all tracks
        command_off: "<0>"
        command_state: "<s>"
        value_template: "{{ value.find('<p1 MAIN>') != -1 }}"
      dcc_ex_reboot_cmd:
        <<: *defaults
        name: "DCC-EX Reboot Command"
        # Reboot DCC-EX server
        command_on: "<D RESET>"
        command_off: ""
      dcc_ex_pause:
        <<: *defaults
        name: "DCC-EX Pause"
        # Pause all automations
        command_on: "</ PAUSE>"
        command_off: "</ RESUME>"
      dcc_ex_emergency_stop_cmd:
        <<: *defaults
        name: "DCC-EX Emergency Stop Command"
        # Emergency stop all locos (without pausing automations)
        command_on: "<!>"
        command_off: ""

      ###############################################
      ## Vossloh 1701
      ###############################################
      dcc_ex_vossloh_engine:
        <<: *defaults
        name: "Vossloh Engine"
        command_on: "<F 4 1 1>"
        command_off: "<F 4 1 0>"
      dcc_ex_vossloh_horn:
        <<: *defaults
        name: "Vossloh Horn"
        command_on: "<F 4 2 1> <F 4 3 1>"   # Enable both low and high horn
        command_off: "<F 4 2 0> <F 4 3 0>"
      dcc_ex_vossloh_cabin_lights:
        <<: *defaults
        name: "Vossloh Cabin Lights"
        command_on: "<F 4 15 1>"
        command_off: "<F 4 15 0>"

      ###############################################
      ## SBB Cargo Re 482
      ###############################################
      dcc_ex_cargo_power_sound:
        <<: *defaults
        name: "Cargo Power Sound"
        command_on: "<F 5 1 1>"
        command_off: "<F 5 1 0>"
      dcc_ex_cargo_cab_start_up:
        <<: *defaults
        name: "Cargo Cab Start Up"
        command_on: "<F 5 7 1>"
        command_off: "<F 5 7 0>"
      dcc_ex_cargo_general_station_sounds:
        <<: *defaults
        name: "Cargo General Station Sounds"
        command_on: "<F 5 20 1>"
        command_off: "<F 5 20 0>"
      dcc_ex_cargo_inspection_lights:
        <<: *defaults
        name: "Cargo Inspection Lights"
        command_on: "<F 5 21 1>"
        command_off: "<F 5 21 0>"

      ###############################################
      ## ROUTES (AUTOMATIONS)
      ###############################################
      dcc_ex_route_300_cmd:
        name: "DCC-EX Route 300 Command"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        command_on: "</ START 300>"
        command_off: ""
        timeout: *telnet_cmd_timeout
      dcc_ex_route_301_cmd:
        name: "DCC-EX Route 301 Command"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        command_on: "</ START 301>"
        command_off: ""
        timeout: *telnet_cmd_timeout

###############################################
## AUTOMATIONS
###############################################
automation:
  # Enable switches based on button presses
  - alias: "DCC-EX Handle Button Presses"
    id: dcc_ex_handle_button_presses
    variables:
      button_switch_map:
        input_button.dcc_ex_emergency_stop: switch.dcc_ex_emergency_stop_cmd
        input_button.dcc_ex_reboot: switch.dcc_ex_reboot_cmd
        input_button.dcc_ex_route_300: switch.dcc_ex_route_300_cmd
        input_button.dcc_ex_route_301: switch.dcc_ex_route_301_cmd
    triggers:
      - trigger: state
        entity_id:
          - input_button.dcc_ex_emergency_stop
          - input_button.dcc_ex_reboot
          - input_button.dcc_ex_route_300
          - input_button.dcc_ex_route_301
    actions:
      - action: switch.turn_on
        data:
          entity_id: "{{ button_switch_map[trigger.entity_id] }}"

  # Disable command switches after 1 second
  - alias: "DCC-EX Disable Command Switches"
    id: dcc_ex_disable_command_switches
    triggers:
      - trigger: state
        entity_id:
          - switch.dcc_ex_emergency_stop_cmd
          - switch.dcc_ex_reboot_cmd
          - switch.dcc_ex_route_300_cmd
          - switch.dcc_ex_route_301_cmd
        to: "on"
        for: "00:00:01"
    variables:
      switch_entity: "{{ trigger.entity_id }}"
    actions:
      - action: switch.turn_off
        target:
          entity_id: "{{ switch_entity }}"

  - alias: "DCC-EX Enable Power on Sunset"
    id: dcc_ex_enable_power_on_sunset
    triggers:
      - trigger: sun
        event: sunset
      - trigger: state
        entity_id: person.sen
        to: "home"
    conditions:
      # For sunset trigger
      - condition: state
        entity_id: person.sen
        state: "home"
      # For person trigger
      - condition: sun
        after: sunset
        before_offset: 00:15:00
      # If night mode is off
      - condition: state
        entity_id: input_boolean.home_night_mode
        state: "off"
    actions:
      - action: switch.turn_on
        target:
          entity_id: switch.dcc_ex_pwr

  # Turn on Locomotive cabin lights on motion
  - alias: "DCC-EX Cabin Lights on Motion"
    id: dcc_ex_vossloh_cabin_lights_on_motion
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id: binary_sensor.kitchen_motion_alarm
    conditions:
      - condition: state
        entity_id: switch.dcc_ex_pwr
        state: "on"
      - condition: template
        value_template: "{{ trigger.to_state.state in ['on', 'off'] }}"
    actions:
      - action: switch.turn_{{ "on" if trigger.to_state.state == "on" else "off" }}
        entity_id: switch.dcc_ex_vossloh_cabin_lights
