######################################################################
# File: dcc-ex.yaml                                                  #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2024-01-21                                                   #
#                                                                    #
# Info: this file contains entities that are associated to the       #
# DCC-EX protocol and my model railway layout.                       #
# More info about DCC-EX API:                                        #
# https://dcc-ex.com/reference/developers/api.html#gsc.tab=0         #
#                                                                    #
# Copyright (c) 2024 Sen Morgan                                      #
######################################################################

###############################################
## SWITCHES
###############################################
switch:
  - platform: telnet
    switches:
      dcc_ex_pwr:
        name: "DCC-EX Power and Loco Lights"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        # Power all tracks and enable loco's lights
        command_on: "<1> <F 4 0 1> <F 5 0 1>"
        # Power off all tracks
        command_off: "<0>"
        timeout: 0.2
      dcc_ex_engine_sound:
        name: "DCC-EX Vossloh Engine Sound"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        # Ebable engine sound on Loco #4
        command_on: "<F 4 1 1>"
        # Disable engine sound
        command_off: "<F 4 1 0>"
        timeout: 0.2
      dcc_ex_horn:
        name: "DCC-EX Horn"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        # Horn on Loco #4 (both LOW and HIGH horns)
        command_on: "<1> <F 4 2 1> <F 4 3 1>"
        # Horn off
        command_off: "<F 4 2 0> <F 4 3 0>"
        timeout: 0.2
      dcc_ex_emergency_stop:
        name: "DCC-EX Emergency Stop"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        # Emergency stop all locos (without disabling power)
        command_on: "<!>"
        command_off: ""
        timeout: 0.2

###############################################
## AUTOMATIONS
###############################################
automation:
  # Disable dcc_ex_emergency_stop switch after 1 second to
  # make it possible to use it as a momentary switch.
  - alias: Disable DCC-EX Emergency Stop switch
    id: disable_dcc_ex_emergency_stop
    mode: restart
    trigger:
      - platform: state
        entity_id: switch.dcc_ex_emergency_stop
        to: 'on'
        for:
          seconds: 1
    action:
      - service: switch.turn_off
        entity_id: switch.dcc_ex_emergency_stop