######################################################################
# File: dcc-ex.yaml                                                  #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2024-01-21                                                   #
#                                                                    #
# Info: this file contains entities that are associated to the       #
# DCC-EX protocol and my model railway layout.                       #
# More info about DCC-EX API:                                        #
# https://dcc-ex.com/reference/developers/api.html#gsc.tab=0         #
#                                                                    #
# Copyright (c) 2024 Sen Morgan                                      #
######################################################################

###############################################
## INPUT BUTTONS
###############################################
input_button:
  dcc_ex_emergency_stop:
    name: "DCC-EX Emergency Stop"
    icon: mdi:alert
  dcc_ex_reboot:
    name: "DCC-EX Reboot"
    icon: mdi:restart

###############################################
## SWITCHES
###############################################
switch:
  - platform: telnet
    switches:
      ###############################################
      ## FUNCTIONS
      ###############################################
      dcc_ex_pwr:
        name: "DCC-EX Power and Loco Lights"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        # Power all tracks and enable loco's lights (and interior lights)
        command_on: "<1> <F 4 0 1> <F 5 0 1> <F 4 15 1>"
        # Power off all tracks
        command_off: "<0>"
        timeout: &telnet_cmd_timeout 0.2
      dcc_ex_engine_sound:
        name: "DCC-EX Vossloh Engine Sound"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        # Ebable engine sound on Loco #4
        command_on: "<F 4 1 1>"
        # Disable engine sound
        command_off: "<F 4 1 0>"
        timeout: *telnet_cmd_timeout
      dcc_ex_horn:
        name: "DCC-EX Horn"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        # Horn on Loco #4 (both LOW and HIGH horns)
        command_on: "<1> <F 4 2 1> <F 4 3 1>"
        # Horn off
        command_off: "<F 4 2 0> <F 4 3 0>"
        timeout: *telnet_cmd_timeout
      dcc_ex_pause:
        name: "DCC-EX Pause"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        # Pause all locos
        command_on: "</ PAUSE>"
        command_off: "</ RESUME>"
        timeout: *telnet_cmd_timeout
      dcc_ex_emergency_stop_cmd:
        name: "DCC-EX Emergency Stop Command"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        # Emergency stop all locos (without disabling power)
        command_on: "<!>"
        command_off: ""
        timeout: *telnet_cmd_timeout
      dcc_ex_reboot_cmd:
        name: "DCC-EX Reboot Command"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        # Reboot DCC-EX server
        command_on: "<D RESET>"
        command_off: ""
        timeout: *telnet_cmd_timeout
      ###############################################
      ## ROUTES (AUTOMATIONS)
      ###############################################
      dcc_ex_route_300:
        name: "DCC-EX Route 300"
        resource: !secret DCC-EX-SERVER-IP
        port: !secret DCC-EX-SERVER-PORT
        # Route 300
        command_on: "</ START 300>"
        command_off: "</ PAUSE>"
        timeout: *telnet_cmd_timeout

###############################################
## AUTOMATIONS
###############################################
automation:
  # Emergency stop if button pushed
  - alias: "Enable dcc_ex_emergency_stop_cmd switch"
    id: enable_dcc_ex_emergency_stop_cmd
    trigger:
      - platform: state
        entity_id: input_button.dcc_ex_emergency_stop
    action:
      - service: switch.turn_on
        entity_id: switch.dcc_ex_emergency_stop_cmd
  # Reboot DCC-EX server if button pushed
  - alias: "Reboot DCC-EX server"
    id: reboot_dcc_ex_server
    trigger:
      platform: state
      entity_id: input_button.dcc_ex_reboot
    action:
      - service: switch.turn_on
        entity_id: switch.dcc_ex_reboot_cmd
  # Disable DCC-EX momentary telnet switches after 1 second
  - alias: "Disable DCC-EX momentary telnet switches"
    id: disable_dcc_ex_momentary_telnet_switches
    trigger:
      - platform: state
        entity_id: switch.dcc_ex_emergency_stop_cmd
        to: "on"
        for: "00:00:01"
      - platform: state
        entity_id: switch.dcc_ex_reboot_cmd
        to: "on"
        for: "00:00:01"
    action:
      - service: switch.turn_off
        entity_id: switch.dcc_ex_emergency_stop_cmd
      - service: switch.turn_off
        entity_id: switch.dcc_ex_reboot_cmd
