######################################################################
# File: home-electricity.yaml                                        #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2026-04-03                                                   #
#                                                                    #
# Info: this file contains automations that are associated to the    #
# Home Assistant electricity monitoring system.                      #
#                                                                    #
# Copyright (c) 2026 Sen Morgan                                      #
######################################################################

###############################################
## SETTINGS AND VARIABLES
###############################################
homeassistant:
  customize:
    package.node_anchors:
      sys_notify_title_info: &sys_notify_title_info "💬 Системное уведомление"
      sys_notify_title_warning: &sys_notify_title_warning "⚠️ Предупреждение"
      sys_notify_title_critical: &sys_notify_title_critical "🚨 Внимание!"

###############################################
## ALERTS
###############################################
alert:
  high_power:
    name: "High Power Consumption"
    entity_id: binary_sensor.high_power_consumption
    state: "on"
    repeat: 60
    notifiers:
      - mobile_app_sen_s25
      - persistent_notification
    title: *sys_notify_title_critical
    message: &high_power_message >
      Внимание! Превышение лимита потребления мощности. Текущий уровень: {{ states('sensor.electricity_meter_power') | int(0) }} Вт.

###############################################
## TEMPLATE ENTITIES
###############################################
template:
  - binary_sensor:
      - name: High Power Consumption
        unique_id: high_power_consumption
        state: "{{ states('sensor.electricity_meter_power') | int(0) > 6000 }}"  # Threshold set to 6kW

  - sensor:
      - name: Grid Consumed Today Cost
        unique_id: grid_consumed_today_cost
        unit_of_measurement: "Kč"
        device_class: monetary
        state_class: total
        # Cote: calculations made 09.2025
        # Fixed part - 223.30 Kč per month, divided by 30.4 days = 7.35 Kč per day
        # Variable part - 5.316 Kč per kWh
        # Total = (7.35 + (5.316 * consumed kWh today)) + 21% VAT
        state: >
          {% set fixed = 7.35 %}
          {% set variable = 5.316 %}
          {% set vat = 0.21 %}
          {% set consumed = states('sensor.grid_consumed_today') | float(0.0) %}
          {{ ((fixed + (variable * consumed)) * (1 + vat)) | round(2, default=0) }}
      - name: Grid Consumed Month Cost
        unique_id: grid_consumed_month_cost
        unit_of_measurement: "Kč"
        device_class: monetary
        state_class: total
        # Fixed part - 223.30 Kč per month
        # Variable part - 5.316 Kč per kWh
        # Total = (223.30 + (5.316 * consumed kWh today)) + 21% VAT
        state: >
          {% set fixed = 223.30 %}
          {% set variable = 5.316 %}
          {% set vat = 0.21 %}
          {% set consumed = states('sensor.grid_consumed_month') | float(0.0) %}
          {{ ((fixed + (variable * consumed)) * (1 + vat)) | round(2, default=0) }}

###############################################
## SENSORS
###############################################
sensor:
  - platform: history_stats
    name: High Power Today
    unique_id: high_power_today
    entity_id: binary_sensor.high_power_consumption
    state: "on"
    type: time
    start: "{{ today_at('00:00:00') }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: High Power Month
    unique_id: high_power_month
    entity_id: binary_sensor.high_power_consumption
    state: "on"
    type: time
    start: "{{ today_at('00:00').replace(day=1) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: High Power Previous Month
    unique_id: high_power_previous_month
    entity_id: binary_sensor.high_power_consumption
    state: "on"
    type: time
    start: "{{ (today_at('00:00').replace(day=1) - timedelta(days=1)).replace(day=1) }}"
    end: "{{ today_at('00:00').replace(day=1) }}"

##############################################
# AUTOMATIONS
##############################################
automation:
  - id: notify_high_power
    alias: "Notify High Power Consumption"
    trigger:
      - platform: state
        entity_id: binary_sensor.high_power_consumption
        to: "on"
        for:
          minutes: 1
    action:
      - action: media_player.play_media
        entity_id: media_player.yandex_station_midi
        data:
          media_content_id: *high_power_message
          media_content_type: text