######################################################################
# File: galaxy_watch.yaml                                              #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2026-02-13                                                   #
#                                                                    #
# Copyright (c) 2026 Sen Morgan                                      #
######################################################################


###############################################
## Automations
###############################################
automation:
  - alias: Galaxy Watch Charger Reenable
    id: galaxy_watch_charger_reenable
    mode: restart
    triggers:
      - trigger: state
        entity_id: person.sen
        to: "home"
      - trigger: time
        at: "09:00:00"
      - trigger: state
        entity_id: input_boolean.silent_mode
        to: "off"
      - trigger: state
        entity_id: input_boolean.home_night_mode
        to: "off"
      - trigger: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 4.0
    conditions:
      - condition: state
        entity_id: switch.galaxy_watch_charger
        state: "off"
      - condition: numeric_state
        entity_id: sensor.galaxy_watch6_classic_r7dh_battery_level
        below: 80
      - condition: state
        entity_id: binary_sensor.people_home
        state: "on"
      - condition: time
        after: "08:00:00"
        before: "21:00:00"
    actions:
      - action: switch.turn_on
        entity_id: switch.galaxy_watch_charger

  - alias: Notification Watch Charged
    id: notification_watch_charged
    trigger:
      - platform: numeric_state
        entity_id: sensor.galaxy_watch6_classic_r7dh_battery_level
        above: 79
    conditions:
      - condition: state
        entity_id: person.sen
        state: "home"
    action:
      - action: switch.turn_off
        entity_id: switch.galaxy_watch_charger
      - action: notify.mobile_app_sen_s25
        data:
          title: "{{ '🔋' }} Часы заряжены"
          message: "Твои Galaxy Watch заряжены уже на 80%!"
      # If silent mode is not enabled, then notify via Yandex Station also
      - if:
          - condition: state
            entity_id: input_boolean.silent_mode
            state: "off"
        then:
          - action: media_player.play_media
            entity_id: media_player.yandex_station_midi
            data:
              media_content_type: text
              media_content_id: "Часы заряжены на 80%"