######################################################################
# File: guest_mode.yaml                                              #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2025-01-27                                                   #
#                                                                    #
# Copyright (c) 2025 Sen Morgan                                      #
######################################################################

###############################################
## INPUT BOOLEAN
###############################################
input_boolean:
  guest_mode:
    # When enabled, the system will ignore presence detection (e.g., it will not turn off lights or heating)
    # while a guest is at home. Controlling lights in the living room from other rooms will be disabled
    # to avoid disturbing the guest.
    name: Guest Mode
    icon: mdi:account-group

###############################################
## INPUT DATETIME
###############################################
input_datetime:
  guest_mode_disable_time:
    name: Guest Mode Disable Time
    has_date: true
    has_time: true

###############################################
## SCRIPTS
###############################################
script:
  enable_guest_mode:
    alias: Enable Guest Mode
    sequence:
      - action: input_boolean.turn_on
        entity_id: input_boolean.guest_mode
      # Turn off the script that could be running at this moment
      - action: script.turn_off
        entity_id: script.turn_off_lights_after_people_leave
      # Set the time when the guest mode will be disabled
      - action: input_datetime.set_datetime
        data:
          entity_id: input_datetime.guest_mode_disable_time
          datetime: "{{ (now().date() + timedelta(days=1)).strftime('%Y-%m-%d') }} 09:00:00"
      - variables:
          message: Гостевой режим активирован до 9:00 утра завтрашнего дня
          # Including an id in the action allows us to identify this script run
          # and not accidentally trigger for other notification actions
          action_update_time: "{{ 'action_update_time' ~ context.id }}"
          action_disable: "{{ 'action_disable' ~ context.id }}"
      - action: media_player.play_media
        entity_id: media_player.yandex_station_midi
        data:
          media_content_id: "{{ message }}"
          media_content_type: text
      - action: notify.mobile_app_sm_s901b
        data:
          title: "👤 Гостевой режим"
          message: "{{ message }}"
          data:
            actions:
              - action: "URI"
                title: 🕘 Сменить время
                icon: mdi:clock-time-eight
                uri: /lovelace/security
              - action: "{{ action_disable }}"
                title: ❌ Отключить
                icon: mdi:account-off
      - wait_for_trigger:
          - trigger: event
            event_type: mobile_app_notification_action
            event_data:
              action: "{{ action_disable }}"
      - if:
          - condition: template
            value_template: "{{ wait.trigger.event.data.action == action_disable }}"
        then:
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.guest_mode
          - action: notify.mobile_app_sm_s901b
            data:
              title: "👤 Гостевой режим"
              message: Гостевой режим отключен

###############################################
## AUTOMATIONS
###############################################
automation:
  - alias: Guest Mode Reset
    id: guest_mode_reset
    mode: restart
    triggers:
      # Trigger on the time when the guest mode should be disabled
      - platform: time
        at: input_datetime.guest_mode_disable_time
      # Trigger when Home Assistant starts to handle the case when the system was disabled/restarted at the time
      # when the guest mode should be disabled
      - platform: homeassistant
        event: start
    conditions:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "on"
      - condition: template # For HA startup trigger
        value_template: >
          {{ as_timestamp(now()) >= as_timestamp(states('input_datetime.guest_mode_disable_time'), 0) }}
    actions:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.guest_mode
      - variables:
          # Including an id in the action allows us to identify this script run
          # and not accidentally trigger for other notification actions
          action_enable_back_on: "{{ 'action_enable_back_on' ~ context.id }}"
      - action: notify.mobile_app_sm_s901b
        data:
          title: "👤 Гостевой режим"
          message: "Гостевой режим выключен автоматически в {{ states('sensor.time') }}. Включить обратно?"
          data:
            actions:
              - action: "{{ action_enable_back_on }}"
                title: ↻ Включить снова
                icon: mdi:account-check
      - wait_for_trigger:
          - trigger: event
            event_type: mobile_app_notification_action
            event_data:
              action: "{{ action_enable_back_on }}"
      - if:
          - condition: template
            value_template: "{{ wait.trigger.event.data.action == action_enable_back_on }}"
        then:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.guest_mode
          # Set the time when the guest mode will be disabled
          - action: input_datetime.set_datetime
            data:
              entity_id: input_datetime.guest_mode_disable_time
              datetime: "{{ (now().date() + timedelta(days=1)).strftime('%Y-%m-%d') }} 09:00:00"
          - action: notify.mobile_app_sm_s901b
            data:
              title: "👤 Гостевой режим"
              message: Гостевой режим включен снова до 9:00 утра завтрашнего дня
