######################################################################
# File: meshtastic.yaml                                              #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2025-12-02                                                   #
#                                                                    #
# Copyright (c) 2025 Sen Morgan                                      #
######################################################################

###############################################
## Automations
###############################################
automation:
  - alias: Meshtastic Echo Morgans Channel
    id: meshtastic_echo_morgans_channel
    mode: single
    triggers:
      - domain: meshtastic
        device_id: 5dd840db1c76b5319a4478ab33c7b33b
        type: channel_message.received
        entity_id: meshtastic.gateway_lrnr_channel_morgans
        trigger: device
    conditions:
      - condition: template
        value_template: '{{ "test" in (trigger.event.data.message | lower) or "ping" in (trigger.event.data.message | lower) }}'
    actions:
      - delay:
          seconds: 2
      - action: meshtastic.broadcast_channel_message
        metadata: {}
        data:
          ack: true
          channel: meshtastic.gateway_lrnr_channel_morgans
          message: "PONG: {{ trigger.event.data.message }}"

  - alias: Meshtastic Echo Home Temperature Sensors
    id: meshtastic_echo_home_temperature_sensors
    mode: single
    triggers:
      - domain: meshtastic
        device_id: 5dd840db1c76b5319a4478ab33c7b33b
        type: channel_message.received
        entity_id: meshtastic.gateway_lrnr_channel_morgans
        trigger: device
    conditions:
      - condition: template
        value_template: '{{ "status" in (trigger.event.data.message | lower) }}'
    actions:
      - delay:
          seconds: 2
      - variables:
          entity_pattern: 'sensor.ble_temperature_atc_.*|sensor.ikea_vindstyrka_.*'  # Pattern to match relevant sensors
          max_message_length: 200  # 200 characters is a common limit for mesh messages
          message_header: "Home Sensors:"  # Header for each message chunk
          message_chunks: >-
            {% set lines = states.sensor | selectattr('entity_id', 'match', entity_pattern) | map(attribute='entity_id') | list %}
            {% set ns = namespace(chunks=[], current=message_header) %}
            {% for line in lines %}
              {% set state_value = states(line) | float(0) | round(2) if (states(line) | is_number) else 'N/A' %}
              {% set state_name = state_attr(line, 'friendly_name') | default(line) %}
              {% set state_time = states[line].last_updated | default('N/A') %}
              {% set row = '🌡' ~(state_value) ~ '°C — ' ~ state_name ~ ' (' ~ (state_time | relative_time) ~ ' ago)' %}
              {% set candidate = ns.current ~ '\n' ~ row %}
              {% if candidate | length > max_message_length and ns.current != message_header %}
                {% set ns.chunks = ns.chunks + [ns.current] %}
                {% set ns.current = message_header ~ '\n' ~ row %}
              {% else %}
                {% set ns.current = candidate %}
              {% endif %}
            {% endfor %}
            {% if ns.current != message_header %}
              {% set ns.chunks = ns.chunks + [ns.current] %}
            {% endif %}
            {% if ns.chunks | length == 0 %}
              {% set ns.chunks = [message_header ~ '\nNo sensor data available'] %}
            {% endif %}
            {{ ns.chunks }}
      - repeat:
          for_each: "{{ message_chunks }}"
          sequence:
            - action: meshtastic.broadcast_channel_message
              metadata: {}
              data:
                ack: true
                channel: meshtastic.gateway_lrnr_channel_morgans
                message: "{{ repeat.item }}"
            - delay:
                seconds: 1
