######################################################################
# File: night_silent_modes.yaml                                      #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2024-02-26                                                   #
#                                                                    #
# Copyright (c) 2024 Sen Morgan                                      #
######################################################################

###############################################
## INPUT BOOLEANS
###############################################
input_boolean:
  silent_mode:
    name: Silent Mode
    icon: mdi:volume-off
  home_night_mode:
    name: Home Night Mode
    icon: mdi:weather-night
  bedroom_lights_and_cover_safety_switch:
    name: Bedroom Lights Safety Switch
    icon: mdi:lightbulb-multiple-off-outline

###############################################
## SCRIPTS
###############################################
script:
  set_silent_mode:
    alias: Set Silent Mode
    sequence:
      # Lower Yandex volume
      - action: script.set_all_yandex_stations_volume_level
        data:
          volume_level: 0.2
      # Notify via 7-Segment Clock that we are in silent mode
      - action: scene.turn_on
        entity_id: scene.7_seg_clock_red
      # Make DCC-EX volume lower
      - action: input_button.press
        target:
          entity_id: input_button.dcc_ex_default_volume
      - action: input_boolean.turn_on
        entity_id:
          # Ensure silent mode is enabled
          - input_boolean.silent_mode
          # Disallow control of bedroom lights and cover
          - input_boolean.bedroom_lights_and_cover_safety_switch
      # Reset child lock
      - action: input_boolean.turn_off
        entity_id: input_boolean.child_lock

  reset_silent_mode:
    alias: Reset Silent Mode
    sequence:
      # Rase Yandex volume
      - action: script.set_all_yandex_stations_volume_level
        data:
          volume_level: 0.4
      # Notify via 7-Segment Clock that we left silent mode
      - action: select.select_option
        data:
          entity_id: select.7_seg_clock_preset
          option: Orange Candle
      # Set DCC-EX max volume
      - action: input_button.press
        target:
          entity_id: input_button.dcc_ex_max_volume
      - action: input_boolean.turn_off
        entity_id:
          # Ensure silent mode is disabled
          - input_boolean.silent_mode
          # Allow control of bedroom lights and cover
          - input_boolean.bedroom_lights_and_cover_safety_switch

  home_night_mode:
    alias: Home Night Mode
    sequence:
      # Decrease WallPanel screen brightness
      - action: scene.turn_on
        entity_id: scene.wallpanel_screen_off
      # Ensure night and silent modes are enabled
      - action: input_boolean.turn_on
        entity_id:
          - input_boolean.home_night_mode
          - input_boolean.silent_mode

  home_day_mode:
    alias: Home Day Mode
    sequence:
      # Rise WallPanel screen brightness
      - action: scene.turn_on
        entity_id: scene.wallpanel_screen_on
      # Ensure night and silent mode are disabled
      - action: input_boolean.turn_off
        entity_id:
          - input_boolean.home_night_mode
          - input_boolean.silent_mode
      - action: switch.turn_on
        entity_id: switch.interactive_cz_map_enable

  cover_correct_up:
    alias: Cover Correct Zero Pozition Up
    sequence:
      - action: mqtt.publish
        data:
          topic: /blinds/set
          payload: "CORRECT_UP"

  cover_correct_down:
    alias: Cover Correct Zero Pozition Down
    sequence:
      - action: mqtt.publish
        data:
          topic: /blinds/set
          payload: "CORRECT_DOWN"

###############################################
## AUTOMATIONS
###############################################
automation:
  - alias: Silent Mode Handler
    id: silent_mode_handler
    triggers:
      - trigger: state
        entity_id: input_boolean.silent_mode
    actions:
      service_template: >
        {% if is_state('input_boolean.silent_mode', 'on') %}
          script.set_silent_mode
        {% else %}
          script.reset_silent_mode
        {% endif %}

  - alias: Night Mode Handler
    id: night_mode_handler
    triggers:
      - trigger: state
        entity_id: input_boolean.home_night_mode
    actions:
      service_template: >
        {% if is_state('input_boolean.home_night_mode', 'on') %}
          script.home_night_mode
        {% else %}
          script.home_day_mode
        {% endif %}

  - alias: Home Enable Night Mode at Evening
    id: home_enable_night_mode_at_evening
    mode: single
    triggers:
      - trigger: state
        entity_id: binary_sensor.bedroom_door_contact
        from: "on"
        to: "off"
        for: 00:00:30
      - trigger: time
        at: "22:00:00"
    conditions:
      - condition: time
        after: "20:00:00"
        before: "03:00:00"
      - condition: state
        entity_id: binary_sensor.people_home
        state: "on"
    actions:
      - action: input_boolean.turn_on
        entity_id:
          - input_boolean.home_night_mode
          - input_boolean.silent_mode

  - alias: Yandex Volume Increased Handler
    id: yandex_volume_increased_handler
    mode: single
    triggers:
      - trigger: state
        entity_id: media_player.yandex_station
      - trigger: state
        entity_id: media_player.yandex_station_midi
    conditions:
      - condition: time
        after: "06:00:00"
        before: "12:00:00"
      - condition: state
        entity_id: input_boolean.silent_mode
        state: "on"
      - condition: template
        value_template: >
          {% set from = trigger.from_state.attributes.volume_level | float(0) %}
          {% set to = trigger.to_state.attributes.volume_level | float(0) %}
          {{ to > from }}
    actions:
      - action: input_boolean.turn_off
        entity_id:
          - input_boolean.home_night_mode
          - input_boolean.silent_mode

  - alias: Good Morning Handler
    id: good_morning_handler
    mode: single
    triggers:
      - trigger: state
        entity_id: binary_sensor.bedroom_door_contact
        from: "off"
        to: "on"
        for: 00:00:30
      - trigger: time
        at: "09:00:00"
      - trigger: state
        entity_id: cover.bedroom
        to: "open"
    conditions:
      - condition: state
        entity_id: input_boolean.home_night_mode
        state: "on"
      - condition: time
        after: "06:00:00"
        before: "12:00:00"
      - condition: state
        entity_id: binary_sensor.bedroom_door_contact
        state: "on"
    actions:
      - action: input_boolean.turn_off
        entity_id:
          - input_boolean.home_night_mode
          - input_boolean.silent_mode

  - alias: Silent Mode by Bedroom Door
    id: silent_mode_by_bedroom_door
    mode: single
    triggers:
      - trigger: state
        entity_id: binary_sensor.bedroom_door_contact
        for: 00:00:30
    conditions:
      - condition: state
        entity_id: input_boolean.home_night_mode
        state: "off"
    actions:
      # If bedroom door closed ("off" state), then turn on silent mode, otherwise turn it off
      - action: input_boolean.turn_{{ "on" if trigger.to_state.state == "off" else "off" }}
        entity_id: input_boolean.silent_mode

  - alias: Prevent Accidental Bedroom Lights ON
    id: prevent_accidental_bedroom_lights_on
    triggers:
      - trigger: state
        entity_id:
          - light.bedroom_ceiling_light
          - light.bedroom_nightlight
        to: "on"
    conditions:
      - condition: state
        entity_id: input_boolean.bedroom_lights_and_cover_safety_switch
        state: "on"
      # Allow the light to be turned on if it was done manually (trigger.to_state.context.user_id is null)
      - condition: template
        value_template: "{{ trigger.to_state.context.user_id != None }}"
    actions:
      - action: light.turn_off
        data:
          entity_id: "{{ trigger.entity_id }}"

  - alias: Prevent Accidental Bedroom Cover Open
    id: prevent_accidental_bedroom_cover_open
    triggers:
      - trigger: state
        entity_id: cover.bedroom
        to: "open"
    conditions:
      - condition: state
        entity_id: input_boolean.bedroom_lights_and_cover_safety_switch
        state: "on"
      # Allow the cover to be opened if it was done manually (trigger.to_state.context.user_id is null)
      - condition: template
        value_template: "{{ trigger.to_state.context.user_id != None }}"
      # Allow the cover to be opened by Yandex Station
      - condition: template
        value_template: !secret TEMPLATE_NOT_A_YANDEX_USER_ID
    actions:
      - action: cover.close_cover
        data:
          entity_id: "{{ trigger.entity_id }}"

  # Prevent accidental volume increase on all Yandex devices in silent mode.
  - alias: Prevent Accidental Yandex Volume Increase at Silent Mode
    id: prevent_accidental_yandex_volume_increase_at_silent_mode
    triggers:
      - trigger: state
        entity_id: media_player.yandex_station
      - trigger: state
        entity_id: media_player.yandex_station_midi
    conditions:
      - condition: state
        entity_id: input_boolean.silent_mode
        state: "on"
      - condition: template
        value_template: >
          {% set from = trigger.from_state.attributes.volume_level | float(0) %}
          {% set to = trigger.to_state.attributes.volume_level | float(0) %}
          {{ to > from and to > 0.4 }}
    actions:
      # Lower Yandex volume
      - action: script.set_all_yandex_stations_volume_level
        data:
          volume_level: 0.2

  # Prevent accidental volume increase on Yandex Mini in normal conditions (not in silent mode).
  # Used to save ears from loud music when children play with the volume buttons.
  - alias: Prevent Accidental Yandex Mini Volume Increase
    id: prevent_accidental_yandex_mini_volume_increase
    mode: restart
    triggers:
      - trigger: state
        entity_id: media_player.yandex_station
    conditions:
      # Allow volume to be changed externally (not by buttons on the device)
      - condition: template
        value_template: "{{ trigger.to_state.context.user_id == None }}"
      - condition: template
        value_template: >
          {% set from = trigger.from_state.attributes.volume_level | float(0) %}
          {% set to = trigger.to_state.attributes.volume_level | float(0) %}
          {{ to > from and to > 0.6 }}
    actions:
      # Lower Yandex volume
      - action: script.set_volume_level_repeatedly
        data:
          media_player: media_player.yandex_station
          volume_level: 0.6

###############################################
## SCENES
###############################################
scene:
  - name: Good Night
    id: good_night
    entities:
      # Turning off all lights is called from script.turn_off_all_lights
      cover.bedroom: closed
      switch.moving_head_power: off
      switch.dcc_ex_pwr: off
      media_player.yandex_station: off
      media_player.yandex_station_midi: off
      media_player.bathroom_google_home_mini: off

  - name: No People Home
    id: no_people_home
    entities:
      # Turning off all lights is called from script.turn_off_all_lights
      media_player.samsung_tv: off
      switch.moving_head_power: off
      switch.dcc_ex_pwr: off
      media_player.yandex_station: off
      media_player.yandex_station_midi: off
      media_player.bathroom_google_home_mini: off

  - name: 7 Seg Clock Red
    id: 7_seg_clock_red
    entities:
      light.7_seg_clock:
        state: on
        effect: Solid
        rgb_color: [255, 0, 0]

  - name: WallPanel Screen Off
    id: wallpanel_screen_off
    entities:
      light.wallpanel_screen:
        state: on
        brightness: 1

  - name: WallPanel Screen On
    id: wallpanel_screen_on
    entities:
      light.wallpanel_screen:
        state: on
        brightness: 255
