######################################################################
# File: notifications.yaml                                           #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2024-05-05                                                   #
#                                                                    #
# Copyright (c) 2024 Sen Morgan                                      #
######################################################################

###############################################
## SETTINGS AND VARIABLES
###############################################
homeassistant:
  customize:
    package.node_anchors:
      sys_notify_title_info: &sys_notify_title_info "💬 Системное уведомление"
      sys_notify_title_warning: &sys_notify_title_warning "⚠️ Предупреждение"
      sys_notify_title_critical: &sys_notify_title_critical "🚨 Внимание!"

###############################################
## BINARY SENSORS
###############################################
binary_sensor:
  - platform: trend
    sensors:
      diesel_price_ono_trend:
        friendly_name: "Diesel Price ONO Trend"
        entity_id: sensor.diesel_price_ono
      gasoline_price_ono_trend:
        friendly_name: "Gasoline Price ONO Trend"
        entity_id: sensor.gasoline_price_ono

###############################################
## SCRIPTS
###############################################
script:
  notify_and_create_persistent_notification:
    alias: Notify and Create Persistent Notification
    sequence:
      - action: notify.mobile_app_sen_s25
        data:
          title: "{{ title }}"
          message: "{{ message }}"
          # If data is not empty, then add it to the notification
          data: >
            {% if data is defined %}
              {{ data }}
            {% else %}
              {}
            {% endif %}
      - action: persistent_notification.create
        data:
          title: "{{ title }}"
          message: "{{ message }}"

###############################################
## AUTOMATIONS
###############################################
automation:
  - id: "notification_snow"
    alias: Notification Snow
    triggers:
      - trigger: numeric_state
        entity_id: sensor.openweathermap_snow
        above: 0
    actions:
      - action: notify.mobile_app_sen_s25
        data:
          title: ❄️ Snow Alert
          message: Должно выпадать {{ states('sensor.openweathermap_snow') }} мм/ч снега в {{ states('sensor.time') }}!
          data:
            tag: WEATHER_ALERT
            notification_icon: mdi:snowflake

  - id: "notification_door_opened"
    alias: Notification Door Opened
    triggers:
      - trigger: state
        entity_id: binary_sensor.hall_door_contact
        to: "on"
    conditions:
      - condition: template
        value_template: >
          {{ not states('person.sen') == 'home'}}
    actions:
      - action: notify.mobile_app_sen_s25
        data:
          title: *sys_notify_title_info
          message: Входная дверь была открыта в {{ states('sensor.time') }}

  - id: "notification_kris_arrived"
    alias: Notification Kris Arrived
    triggers:
      - entity_id: person.kris
        to: home
        trigger: state
    conditions:
      - condition: state
        entity_id: input_boolean.home_night_mode
        state: "off"
    actions:
      - data:
          title: "{{ '👩‍🦰' }} Семейное уведомление"
          message: Кристина пришла домой в {{ states('sensor.time') }}
        action: notify.mobile_app_sen_s25
      - if:
          - condition: template
            value_template: "{{ is_state('person.sen', 'home') }}"
        then:
          - entity_id: script.notify_via_kitchen_spotlights
            action: script.turn_on
          - if:
              - condition: state
                entity_id: switch.asus_pc
                state: "on"
            then:
              - target:
                  entity_id: select.pc_backlight_preset
                data:
                  option: Alarm
                action: select.select_option
              - delay: "00:00:10"
              - target:
                  entity_id: select.pc_backlight_preset
                data:
                  option: Gender
                action: select.select_option


  - id: "notification_diesel_price_changed"
    alias: Notification Diesel Price Changed
    triggers:
      - trigger: state
        entity_id: sensor.diesel_price_ono
    conditions:
      - condition: template
        value_template: >
          {{ trigger.from_state.state != trigger.to_state.state }}
      - condition: template
        value_template: >
          {{ is_number(trigger.from_state.state) and is_number(trigger.to_state.state) }}
    actions:
      - action: script.notify_and_create_persistent_notification
        data:
          title: *sys_notify_title_info
          message: >
            Цена дизеля {{ 'упала' if trigger.from_state.state | float(0) > trigger.to_state.state | float(0) else 'возрасла' }}
            с {{ trigger.from_state.state }} до {{ trigger.to_state.state }} Kč/L
          data:
            actions:
              - action: "URI"
                title: 📈 Open Chart
                uri: "/lovelace/diesel-price"

  - id: "notification_gasoline_price_changed"
    alias: Notification Gasoline Price Changed
    triggers:
      - trigger: state
        entity_id: sensor.gasoline_price_ono
    conditions:
      - condition: template
        value_template: >
          {{ trigger.from_state.state != trigger.to_state.state }}
      - condition: template
        value_template: >
          {{ is_number(trigger.from_state.state) and is_number(trigger.to_state.state) }}
    actions:
      - action: notify.mobile_app_sm_s931b
        data:
          title: *sys_notify_title_info
          message: >
            Цена бензина {{ 'упала' if trigger.from_state.state | float(0) > trigger.to_state.state | float(0) else 'возрасла' }}
            с {{ trigger.from_state.state }} до {{ trigger.to_state.state }} Kč/L
          data:
            actions:
              - action: "URI"
                title: 📈 Open Chart
                uri: "/lovelace/gasoline-price"

  - id: "notification_solar_panel_power_above_threshold"
    alias: Notification Solar Panel Power Above Threshold
    triggers:
      - trigger: numeric_state
        entity_id: sensor.solar_panel_power
        above: 40
        for: "00:05:00"
    actions:
      - action: notify.mobile_app_sen_s25
        data:
          title: "🌞 Солнечная панель"
          message: "Мощность выше порога: {{ states('sensor.solar_panel_power') }} W"

  # Notify on washing finish
  - id: "notification_washing_finish"
    alias: Notification Washing Finish
    triggers:
      - trigger: state
        entity_id: sensor.washing_machine_washer_job_state
        to: "finish"
    # Condition: only if the washing duration is less than 4 hours (otherwise, it's likely a SmartThings integration issue)
    conditions:
      - condition: template
        value_template: >
          {{ (as_timestamp(now(), 0) - as_timestamp(states.sensor.washing_machine_washer_job_state.last_changed, 0)) < 14400 }}
    actions:
      - action: script.yandex_joke_after_washing_clothes

  - id: "notification_shopping_list_sen"
    alias: Notification Shopping List for Sen
    description: Shopping list reminder when Sen enters the supermarket
    mode: single
    trigger:
      - platform: state
        entity_id: person.sen
        to: "JIP"
        for: "00:02:00"
    condition:
      - condition: numeric_state
        entity_id: todo.shopping_list
        above: 0
    action:
      - action: script.update_shopping_list
      - action: notify.mobile_app_sen_s25
        data:
          message: "🛒 Открыть список покупок?"
          data:
            clickAction: /todo?entity_id=todo.shopping_list
            url: /todo?entity_id=todo.shopping_list

  - id: "notification_shopping_list_kris"
    alias: Notification Shopping List for Kris
    description: Shopping list reminder when Kris enters the supermarket
    mode: single
    trigger:
      - platform: state
        entity_id: person.kris
        to: "JIP"
        for: "00:02:00"
    condition:
      - condition: numeric_state
        entity_id: todo.shopping_list
        above: 0
    action:
      - action: script.update_shopping_list
      - action: notify.mobile_app_sm_s931b
        data:
          message: "🛒 Открыть список покупок?"
          data:
            clickAction: /todo?entity_id=todo.shopping_list
            url: /todo?entity_id=todo.shopping_list

  - id: "weather_forecast_alert_helper"
    alias: Weather Forecast Alert Helper
    mode: single
    triggers:
      - trigger: time_pattern
        hours: "1"
    actions:
      - variables:
          weather_entity: weather.home_assistant_blue
          temp_unit: "{{ state_attr(weather_entity, 'temperature_unit') }}"
          notify_group: mobile_app_sen_s25
          enable_snow: true
          enable_rain: true
          enable_cold: true
          enable_hot: false
          low_temp_threshold: 0
          high_temp_threshold: 100
          num_hours_threshold: 2
          num_hours_lookahead: 12
        alias: Define variables from input params
      - action: weather.get_forecasts
        metadata: {}
        data:
          type: hourly
        target:
          entity_id: "{{ weather_entity }}"
        response_variable: action_response
        alias: Get hourly weather for given entity
      - variables:
          forecast: "{{ action_response[weather_entity]['forecast'][:num_hours_lookahead] }}"
          datetimes: >-
            {{ forecast | map(attribute='datetime') | map('as_datetime') |
            map('as_local') | list }}
          temps: "{{ forecast | map(attribute='temperature') | list }}"
          min_temp: "{{ temps | min }}"
          max_temp: "{{ temps | max }}"
          min_temp_idx: "{{ temps.index(min_temp) }}"
          max_temp_idx: "{{ temps.index(max_temp) }}"
          min_temp_hour: "{{ forecast[min_temp_idx]['datetime'] | as_datetime | as_local }}"
          max_temp_hour: "{{ forecast[max_temp_idx]['datetime'] | as_datetime | as_local }}"
          avg_temp: "{{ temps | average | round(1) }}"
          cold_hours: >-
            {{ forecast | selectattr('temperature', 'le', low_temp_threshold) | list
            }}
          hot_hours: >-
            {{ forecast | selectattr('temperature', 'ge', high_temp_threshold) |
            list }}
          snowy_hours: >-
            {{ forecast | selectattr('condition', 'search', '(?i)snow|flurr(y|ies)')
            | list }}
          rainy_hours: "{{ forecast | selectattr('condition', 'search', '(?i)rain') | list }}"
          precip_prob_snowy_hours: "{{ snowy_hours | map(attribute='precipitation_probability') | list }}"
          precip_prob_rainy_hours: "{{ rainy_hours | map(attribute='precipitation_probability') | list }}"
          cold_alert: "{{ enable_cold and cold_hours | count > num_hours_threshold }}"
          hot_alert: "{{ enable_hot and hot_hours | count > num_hours_threshold }}"
          rain_alert: "{{ enable_rain and rainy_hours | count > num_hours_threshold }}"
          snow_alert: "{{ enable_snow and snowy_hours | count > num_hours_threshold }}"
        alias: Parse response and define new variables
      - alias: If any weather conditions warrant notification
        condition: template
        value_template: "{{ cold_alert or rain_alert or snow_alert or hot_alert}}"
      - variables:
          notification_message: >
            {% macro format_datetime(d) %}{{ d | as_timestamp |
            timestamp_custom("%I:%M %p") }}{% endmacro %}


            Over the next {{ num_hours_lookahead }} hours:

            {% if cold_alert %}

            Temperature: Temps will dip below {{ low_temp_threshold }}{{ temp_unit
            }} for {{ cold_hours | count }} hours, initially reaching a minimum of
            {{ min_temp }}{{ temp_unit }} at {{format_datetime(min_temp_hour)}}
            (avg={{ avg_temp }}{{ temp_unit }}).{%endif%}

            {%- if hot_alert %}

            Temperature: Temps will rise_above {{ high_temp_threshold }}{{ temp_unit
            }} for {{ hot_hours | count }} hours, initially reaching a maximum of {{
            max_temp }}{{ temp_unit }} at {{format_datetime(max_temp_hour)}} (avg={{
            avg_temp }}{{ temp_unit }}).{%endif%}

            {%- if rain_alert %}

            Rain: It will be rainy for {{ rainy_hours | count }} hours (max_prob={{
            (precip_prob_rainy_hours or [0]) | max }}%,
            avg_prob={{(precip_prob_rainy_hours or [0]) | average | round(1) }}%).
            {% endif%}

            {%- if snow_alert %}

            Snow: It will be snowy for {{ snowy_hours | count }} hours (max_prob={{
            (precip_prob_snowy_hours or [0]) | max }}%,
            avg_prob={{(precip_prob_snowy_hours or [0]) | average | round(1) }}%).
            {% endif%}
          notification_title: >-
            Weather alert: {{ ["Temperature" if (cold_alert or hot_alert), "Rain" if
            rain_alert, "Snow" if snow_alert] | select() | join(", ") }}
      - action: notify.{{ notify_group }}
        metadata: {}
        data:
          message: "{{ notification_message }}"
          title: "{{ notification_title }}"
          data:
            ttl: 0
            priority: high
            tag: WEATHER_ALERT
            sticky: true
            clickAction: entityId:{{ weather_entity }}
            notification_icon: mdi:weather-cloudy-alert

  - id: "notification_github_repo_stars_changed"
    alias: Notification GitHub Repo Stars Changed
    trigger:
      - trigger: state
        entity_id:
          - sensor.senmorgan_ex_habridge_stars
          - sensor.senmorgan_home_assistant_config_stars
    condition:
      - condition: template
        value_template: >
          {{ trigger.from_state.state != trigger.to_state.state }}
    action:
      - action: notify.mobile_app_sen_s25
        data:
          title: "⭐ GitHub Repository Stars"
          message: >
            Репозиторий {{ state_attr(trigger.entity_id, 'friendly_name') | replace(' Stars', '') }}
            {{ 'получил' if trigger.from_state.state | int < trigger.to_state.state | int else 'потерял' }}
            звезду!
            Звёзд сейчас: {{ trigger.to_state.state }} (было: {{ trigger.from_state.state }})
