######################################################################
# File: plants.yaml                                                  #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2024-01-28                                                   #
#                                                                    #                                                                    #
# Copyright (c) 2024 Sen Morgan                                      #
######################################################################

###############################################
## INPUT NUMBERS
###############################################
input_number:
  moisture_low_threshold:
    name: Moisture Low Threshold
    min: 0
    max: 100
    step: 5.0

###############################################
## AUTOMATIONS
###############################################
automation:
  - alias: Notify on Low Plant Moisture Levels
    id: "notify_on_low_plant_moisture_levels"
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.ble_moisture_coffee_tree
        below: input_number.moisture_low_threshold
        for: 00:10:00
      - platform: numeric_state
        entity_id: sensor.ble_moisture_fikus_benjamin
        below: input_number.moisture_low_threshold
        for: 00:10:00
      - platform: numeric_state
        entity_id: sensor.ble_moisture_monstera_adansonii
        below: input_number.moisture_low_threshold
        for: 00:10:00
      - platform: numeric_state
        entity_id: sensor.ble_moisture_yucca
        below: input_number.moisture_low_threshold
        for: 00:10:00
    action:
      - service: persistent_notification.create
        data:
          title: "{{ '🪴' }} Домашние цветы"
          message: Нужно полить {{ trigger.to_state.name }}. Текущая влажность {{ trigger.to_state.state }}%
      - service: notify.mobile_app_sm_s901b
        data:
          title: "{{ '🪴' }} Домашние цветы"
          message: Нужно полить {{ trigger.to_state.name }}. Текущая влажность {{ trigger.to_state.state }}%

