######################################################################
# File: plants.yaml                                                  #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2024-01-28                                                   #
#                                                                    #                                                                    #
# Copyright (c) 2024 Sen Morgan                                      #
######################################################################

###############################################
## INPUT NUMBERS
###############################################
input_number:
  moisture_low_threshold:
    name: Moisture Low Threshold
    min: 0
    max: 100
    step: 5.0

###############################################
## INPUT TEXTS
###############################################
input_text:
  plants_to_water:
    name: Plants to Water
    initial: ""

###############################################
## AUTOMATIONS
###############################################
automation:
  - alias: Update Plants to Water on Sensor Change
    id: "update_plants_to_water_on_sensor_change"
    mode: single
    max_exceeded: silent
    trigger:
      - platform: time_pattern
        minutes: "/10"
    action:
      - action: python_script.update_plants_to_water

  - alias: Notify on Plants to Water
    id: "notify_on_plants_to_water"
    mode: single
    trigger:
      - platform: state
        entity_id: input_text.plants_to_water
    condition:
      - condition: template
        value_template: "{{ states('input_text.plants_to_water') != '' }}"
      # After 18:00 on weekdays or after 09:00 on weekends
      - condition: or
        conditions:
          - condition: time
            after: "18:00:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
          - condition: time
            after: "09:00:00"
            weekday:
              - sat
              - sun
    action:
      - action: persistent_notification.create
        data:
          title: "{{ '🪴' }} Домашние цветы"
          message: "Нужно полить следующие растения: {{ states('input_text.plants_to_water') }}"
      - action: notify.mobile_app_sm_s901b
        data:
          title: "{{ '🪴' }} Домашние цветы"
          message: "Нужно полить следующие растения: {{ states('input_text.plants_to_water') }}"
