######################################################################
# File: plants.yaml                                                  #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2024-01-28                                                   #
#                                                                    #                                                                    #
# Copyright (c) 2024 Sen Morgan                                      #
######################################################################

###############################################
## INPUT NUMBERS
###############################################
input_number:
  moisture_low_threshold:
    name: Moisture Low Threshold
    min: 0
    max: 100
    step: 5.0

###############################################
## INPUT TEXTS
###############################################
input_text:
  plants_to_water:
    name: Plants to Water
    initial: ""

###############################################
## SCHEDULERS
###############################################
schedule:
  plant_watering_notification:
    name: "Plant Watering Notification"
    monday: &watering_schedule_weekdays
      - from: "17:00:00"
        to: "21:00:00"
    tuesday: *watering_schedule_weekdays
    wednesday: *watering_schedule_weekdays
    thursday: *watering_schedule_weekdays
    friday: *watering_schedule_weekdays
    saturday: &watering_schedule_weekends
      - from: "09:00:00"
        to: "21:00:00"
    sunday: *watering_schedule_weekends

###############################################
## AUTOMATIONS
###############################################
automation:
  - alias: Update Plants to Water on Sensor Change
    id: "update_plants_to_water_on_sensor_change"
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: time_pattern
        minutes: "/10"
    actions:
      - action: python_script.update_plants_to_water

  - alias: Notify on Plants to Water
    id: "notify_on_plants_to_water"
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id: input_text.plants_to_water
    conditions:
      - condition: template
        value_template: "{{ states('input_text.plants_to_water') | length > 0 }}"
      - condition: state
        entity_id: schedule.plant_watering_notification
        state: "on"
    actions:
      # Notify via mobile app and create persistent notification
      - action: script.notify_and_create_persistent_notification
        data:
          title: "🪴 Домашние цветы"
          message: "Нужно полить следующие растения: {{ states('input_text.plants_to_water') }}"
