######################################################################
# File: tags.yaml                                                    #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2024-02-08                                                   #
#                                                                    #                                                                    #
# Copyright (c) 2024 Sen Morgan                                      #
######################################################################

###############################################
## INPUT BOOLEANS
###############################################
input_boolean:
  show_cameras_in_lovelace:
    name: Show Cameras in Lovelace
    icon: mdi:camera

###############################################
## AUTOMATIONS
###############################################
automation:
  - alias: Tag Near PC was scanned
    id: tag_near_pc_was_scanned
    mode: single
    triggers:
      - trigger: tag
        tag_id: c45d3b71-2ade-45e3-8663-f0028f52b01d
    actions:
      - action: input_boolean.toggle
        target:
          entity_id: input_boolean.show_cameras_in_lovelace
      - action: notify.mobile_app_sm_s901b
        data:
          title: "👁️ Режим камер"
          message: >-
            {% if is_state('input_boolean.show_cameras_in_lovelace', 'on') %}
              Камеры включены
            {% else %}
              Камеры выключены
            {% endif %}

  - alias: Reenable Cameras if Hided
    id: reenable_cameras_if_hided
    mode: single
    triggers:
      - trigger: state
        entity_id: input_boolean.show_cameras_in_lovelace
        to: "off"
        for: "01:00:00"
    actions:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.show_cameras_in_lovelace
      - action: notify.mobile_app_sm_s901b
        data:
          title: "👁️ Режим камер"
          message: "Камеры включены автоматически в {{ states('sensor.time') }}"

  - alias: Tag Near Entrance was scanned
    id: tag_near_entrance_was_scanned
    mode: restart
    triggers:
      - trigger: tag
        tag_id: 5954e702-f87d-4955-969c-5231af33ece8
    actions:
      - action: script.enable_guest_mode
