######################################################################
# File: tags.yaml                                                  #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2024-02-08                                                   #
#                                                                    #                                                                    #
# Copyright (c) 2024 Sen Morgan                                      #
######################################################################

###############################################
## AUTOMATIONS
###############################################
automation:
  - alias: Tag Near PC was scanned
    id: tag_near_pc_was_scanned
    mode: single
    triggers:
      - trigger: tag
        tag_id: c45d3b71-2ade-45e3-8663-f0028f52b01d
    actions:
      - action: input_boolean.toggle
        target:
          entity_id: input_boolean.show_cameras_in_lovelace
      - action: notify.mobile_app_sm_s901b
        data:
          title: "👁️ Режим камер"
          message: >-
            {% if is_state('input_boolean.show_cameras_in_lovelace', 'on') %}
              Камеры включены
            {% else %}
              Камеры выключены
            {% endif %}

  - alias: Reenable Cameras if Hided
    id: reenable_cameras_if_hided
    mode: single
    triggers:
      - trigger: state
        entity_id: input_boolean.show_cameras_in_lovelace
        to: "off"
        for: "01:00:00"
    actions:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.show_cameras_in_lovelace
      - action: notify.mobile_app_sm_s901b
        data:
          title: "👁️ Режим камер"
          message: "Камеры включены автоматически в {{ states('sensor.time') }}"

  - alias: Tag Near Entrance was scanned
    id: tag_near_entrance_was_scanned
    mode: restart
    triggers:
      - trigger: tag
        tag_id: 5954e702-f87d-4955-969c-5231af33ece8
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.guest_mode
      # Turn off the script that could be running at this moment
      - action: script.turn_off
        entity_id: script.turn_off_lights_after_people_leave
      - variables:
          message: Включен гостевой режим - термостат и свет не будут отключены после ухода.
          # Including an id in the action allows us to identify this script run
          # and not accidentally trigger for other notification actions
          action_disable: "{{ 'action_disable' ~ context.id }}"
      - action: media_player.play_media
        entity_id: media_player.yandex_station_midi
        data:
          media_content_id: "{{ message }}"
          media_content_type: text
      - action: notify.mobile_app_sm_s901b
        data:
          title: "👤 Гостевой режим"
          message: "{{ message }}"
          data:
            actions:
              - action: "{{ action_disable }}"
                title: ❌ Отключить обратно
                icon: mdi:account-off
      - wait_for_trigger:
          - trigger: event
            event_type: mobile_app_notification_action
            event_data:
              action: "{{ action_disable }}"
      - if:
          - condition: template
            value_template: "{{ wait.trigger.event.data.action == action_disable }}"
        then:
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.guest_mode
          - action: notify.mobile_app_sm_s901b
            data:
              title: "👤 Гостевой режим"
              message: Гостевой режим отключен

  - alias: Ignore People Presence reset
    id: guest_mode_reset
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.people_home
        to: "on"
        for: "00:15:00"
    conditions:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "on"
    actions:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.guest_mode
      - variables:
          # Including an id in the action allows us to identify this script run
          # and not accidentally trigger for other notification actions
          action_enable_back_on: "{{ 'action_enable_back_on' ~ context.id }}"
      - action: notify.mobile_app_sm_s901b
        data:
          title: "👤 Гостевой режим"
          message: "Гостевой режим выключен автоматически в {{ states('sensor.time') }}. Включить обратно?"
          data:
            actions:
              - action: "{{ action_enable_back_on }}"
                title: ↻ Включить снова
                icon: mdi:account-check
      - wait_for_trigger:
          - trigger: event
            event_type: mobile_app_notification_action
            event_data:
              action: "{{ action_enable_back_on }}"
      - if:
          - condition: template
            value_template: "{{ wait.trigger.event.data.action == action_enable_back_on }}"
        then:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.guest_mode
          - action: notify.mobile_app_sm_s901b
            data:
              title: "👤 Гостевой режим"
              message: "Гостевой режим включен снова в {{ states('sensor.time') }}"
