######################################################################
# File: yandex_automations.yaml                                      #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2025-01-23                                                   #
#                                                                    #
# Copyright (c) 2025 Sen Morgan                                      #
######################################################################

###############################################
## AUTOMATIONS
###############################################
automation:
  - id: "sync_shopping_list"
    alias: Sync Shopping List
    mode: single
    triggers:
      - trigger: state
        entity_id: binary_sensor.people_home
        to: "off"
        for: 00:05:00
    actions:
      # Save actual volume
      - action: input_number.set_value
        target:
          entity_id: input_number.volume_yandex_station
        data:
          value: "{{ state_attr('media_player.yandex_station_midi', 'volume_level')}}"
      # Repeat the command to ensure that the volume is muted
      - repeat:
          while:
            - condition: template
              value_template: "{{ not is_state_attr('media_player.yandex_station_midi', 'volume_level', 0.01) }}"
            - condition: template
              value_template: "{{ repeat.index <= 3 }}"
          sequence:
            - action: media_player.volume_set
              data:
                entity_id: media_player.yandex_station_midi
                volume_level: 0.01
            - delay: 0.5
      - action: script.turn_on
        entity_id: script.update_shopping_list
      - delay: 1
      - action: media_player.play_media
        entity_id: media_player.yandex_station_midi
        data:
          media_content_id: stop
          media_content_type: command
      - delay: 1
      # Repeat the command to ensure that the volume is muted
      - repeat:
          while:
            - condition: template
              value_template: "{{ not is_state_attr('media_player.yandex_station_midi', 'volume_level', states('input_number.volume_yandex_station')) }}"
            - condition: template
              value_template: "{{ repeat.index <= 3 }}"
          sequence:
            - action: media_player.volume_set
              data:
                entity_id: media_player.yandex_station_midi
                volume_level: "{{ states('input_number.volume_yandex_station')}}"
            - delay: 1
