######################################################################
# File: zha_devices_actions.yaml                                     #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2023-06-14                                                   #
#                                                                    #                                                                    #
# Copyright (c) 2023 Sen Morgan                                      #
######################################################################

###############################################
## AUTOMATIONS
###############################################
automation:

###############################################
## Aqara Switch Automations
###############################################
- id: "Aqara Switch 1 Handler"
  alias: Aqara Switch 1 Handler
  mode: restart
  max: 20
  # max_exceeded: silent
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        # Aqara Switch 1
        device_id: "6559eaaf60c9624465f762290ff9e825"
  action:
    - variables:
        command: "{{ trigger.event.data.command }}"
    - choose:
        - conditions:
            - "{{ command == 'single' }}"
          sequence:
            - service: light.turn_off
              entity_id: all
            - service: scene.turn_on
              entity_id: scene.good_night
            - service: script.turn_on
              entity_id: script.home_night_mode
        - conditions:
            - "{{ command == 'double' }}"
          sequence:
            - service: light.toggle
              entity_id: light.bedroom_nightlight
        - conditions:
            - "{{ command == 'hold' }}"
          sequence:
            - service: cover.open_cover
              entity_id: cover.bedroom
            - service: script.turn_on
              entity_id: script.home_day_mode
      default: []

###############################################
## Aqara Cube Automations
###############################################
- id: "Aqara_Cube_Flip_90"
  alias: Aqara Cube Flip 90
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.aqara_cube_1_action
      to: "flip90"
  condition:
    - condition: state
      entity_id: input_boolean.cube_1_control
      state: "on"
  action:
    - service: light.toggle
      entity_id: light.string_lights

- id: "Aqara_Cube_Flip_180"
  alias: Aqara Cube Flip 180
  trigger:
    - platform: state
      entity_id: sensor.aqara_cube_1_action
      to: "flip180"
  condition:
    - condition: state
      entity_id: input_boolean.cube_1_control
      state: "on"
  action:
    - service: light.toggle
      entity_id: light.floor_lamp

- id: "Aqara_Cube_Shake"
  alias: Aqara Cube Shake
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.aqara_cube_1_action
      to: "shake"
  condition:
    - condition: state
      entity_id: input_boolean.cube_1_control
      state: "on"
  action:
    - service: light.turn_off
      entity_id: all

- id: "Aqara_Cube_Tap"
  alias: Aqara Cube Tap
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.aqara_cube_1_action
      to: "tap"
  condition:
    - condition: state
      entity_id: input_boolean.cube_1_control
      state: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.movies

- id: "Aqara_Cube_Slide"
  alias: Aqara Cube Slide
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.aqara_cube_1_action
      to: "slide"
  condition:
    - condition: state
      entity_id: input_boolean.cube_1_control
      state: "on"
  action:
    - service: light.toggle
      entity_id: light.mi_desk_lamp

- id: "Aqara_Cube_Rotate"
  alias: Aqara Cube Rotate
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.aqara_cube_1_action
      to: "rotate_left"
    - platform: state
      entity_id: sensor.aqara_cube_1_action
      to: "rotate_right"
  condition:
    - condition: state
      entity_id: input_boolean.cube_1_control
      state: "on"
  action:
    - service: light.turn_on
      entity_id: light.mi_desk_lamp
      data_template:
        brightness:
          "{% set suggested = state_attr('light.mi_desk_lamp', 'brightness')\
          \ | int + \n  state_attr('sensor.aqara_cube_1_action', 'angle') | int + 1\
          \ %}\n{% if suggested > 0 %} {{ suggested }} {% else %} 1 {% endif %}\n"
