######################################################################
# File: zha_devices_actions.yaml                                     #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2023-06-14                                                   #
#                                                                    #                                                                    #
# Copyright (c) 2023 Sen Morgan                                      #
#                                                                    #
# Note:                                                              #
# Device IDs are unique and could be found in:                       #
# Developer Tools → Events → Listen to events → "zha_event".         #
# After some action with device it must be loged there.              #
#                                                                    #
######################################################################

###############################################
## INPUT BOOLEANS
###############################################
input_boolean:
  cube_1_control:
    name: Cube Control
    icon: mdi:gesture-double-tap
    # icon: mdi:cube-outline
  light_brightness:
    name: Light Brightness
    icon: mdi:lightbulb-on-outline
  child_lock:
    name: Child Lock
    icon: mdi:lock
    initial: off

###############################################
## AUTOMATIONS
###############################################
automation:
  ###############################################
  ## Aqara Switch Automations
  ###############################################
  - alias: Aqara Switch 1 Handler
    id: "aqara_switch_1_handler"
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          # Aqara Switch 1
          device_id: "6559eaaf60c9624465f762290ff9e825"
    action:
      - variables:
          command: "{{ trigger.event.data.command }}"
      - choose:
          - conditions:
              - "{{ command == 'single' }}"
            sequence:
              - if:
                  - condition: state
                    entity_id: input_boolean.child_lock
                    state: "off"
                then:
                  - service: light.turn_off
                    entity_id: all
                  - service: scene.turn_on
                    entity_id: scene.good_night
                  - service: script.turn_on
                    entity_id: script.home_night_mode
                else:
                  - service: cover.toggle
                    entity_id: cover.bedroom
          - conditions:
              - "{{ command == 'double' }}"
            sequence:
              - service: light.toggle
                entity_id: light.bedroom_nightlight
          - conditions:
              - "{{ command == 'hold' }}"
            sequence:
              - service: cover.open_cover
                entity_id: cover.bedroom
              - if:
                  - condition: state
                    entity_id: input_boolean.child_lock
                    state: "off"
                then:
                  - service: script.turn_on
                    entity_id: script.home_day_mode
        default: []

  ###############################################
  ## Aqara Cube Automations
  ###############################################

  - alias: Aqara Cube 1 Handler
    id: "aqara_cube_1_handler"
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          # Aqara Cube 1
          device_id: "48fad66663fc601ed1a63ac01e804fab"
    action:
      - if:
          - condition: state
            entity_id: input_boolean.cube_1_control
            state: "on"
        then:
          - variables:
              command: "{{ trigger.event.data.command }}"
              flip_degrees: "{{ trigger.event.data.args.flip_degrees if trigger.event.data.args.flip_degrees is defined else 0 }}"
              relative_degrees: "{{ trigger.event.data.args.relative_degrees if trigger.event.data.args.relative_degrees is defined else 0 }}"
          - choose:
              - conditions:
                  - "{{ flip_degrees == 90 }}"
                sequence:
                  - service: light.toggle
                    entity_id: light.string_lights
              - conditions:
                  - "{{ flip_degrees == 180 }}"
                sequence:
                  - service: light.toggle
                    entity_id: light.floor_lamp
              - conditions:
                  - "{{ command == 'shake' }}"
                sequence:
                  - service: light.turn_off
                    entity_id: all
              - conditions:
                  - "{{ command == 'tap' }}"
                sequence:
                  - service: scene.turn_on
                    entity_id: scene.movies
              - conditions:
                  - "{{ command == 'slide' }}"
                sequence:
                  - service: light.toggle
                    entity_id: light.mi_desk_lamp
              - conditions:
                  - "{{ command == 'rotate_left' or command == 'rotate_right' }}"
                  - "{{ is_state('light.mi_desk_lamp', 'on') }}"
                sequence:
                  - service: light.turn_on
                    entity_id: light.mi_desk_lamp
                    data_template:
                      brightness:
                        "{% set suggested = state_attr('light.mi_desk_lamp', 'brightness')\
                        \ | int + \n  relative_degrees | int + 1\
                        \ %}\n{% if suggested > 0 %} {{ suggested }} {% else %} 1 {% endif %}\n"

  ###############################################
  ## Floorlamp Tradfri Switch Control
  ###############################################
  - alias: Tradfri Switch 1 Handler
    id: "tradfri_switch_1_handler"
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          # Tradfri Switch 1
          device_id: "a64c98fa9b0c36e96ebe42160fcf78b5"
    action:
      - variables:
          command: "{{ trigger.event.data.command }}"
      - choose:
          - conditions:
              - "{{ command == 'on' }}"
            sequence:
              - service: light.turn_on
                entity_id: light.floor_lamp
          - conditions:
              - "{{ command == 'off' }}"
            sequence:
              - service: light.turn_off
                entity_id: light.floor_lamp
          - conditions:
              - "{{ command == 'move_with_on_off' }}"
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.light_brightness
              - service: python_script.change_attribute_light_smoothly
                data:
                  light_id: light.floor_lamp
                  input_boolean: input_boolean.light_brightness
                  delta: 10
          - conditions:
              - "{{ command == 'move' }}"
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.light_brightness
              - service: python_script.change_attribute_light_smoothly
                data:
                  light_id: light.floor_lamp
                  input_boolean: input_boolean.light_brightness
                  delta: -10
          - conditions:
              - "{{ command == 'stop_with_on_off' }}"
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.light_brightness
