######################################################################
# File: zha_devices_actions.yaml                                     #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2023-06-14                                                   #
#                                                                    #                                                                    #
# Copyright (c) 2023 Sen Morgan                                      #
#                                                                    #
# Note:                                                              #
# Device IDs are unique and could be found in:                       #
# Developer Tools → Events → Listen to events → "zha_event".         #
# After some action with device it must be loged there.              #
#                                                                    #
######################################################################

###############################################
## INPUT BOOLEANS
###############################################
input_boolean:
  cube_1_control:
    name: Cube Control
    icon: mdi:gesture-double-tap
  child_lock:
    name: Child Lock
    icon: mdi:lock
    initial: off

###############################################
## AUTOMATIONS
###############################################
automation:
  ###############################################
  ## Aqara Bedroom Switch
  ###############################################
  - alias: Aqara Bedroom Switch Handler
    id: "aqara_bedroom_switch_handler"
    mode: restart
    triggers:
      - trigger: event
        event_type: zha_event
        event_data:
          # Aqara Switch 1
          device_id: "6559eaaf60c9624465f762290ff9e825"
    actions:
      - variables:
          command: "{{ trigger.event.data.command }}"
      - choose:
          - conditions:
              - "{{ command == 'single' }}"
            sequence:
              - if:
                  - condition: state
                    entity_id: input_boolean.child_lock
                    state: "off"
                then:
                  - action: script.activate_night_mode
          - conditions:
              - "{{ command == 'double' }}"
            sequence:
              - if:
                  - condition: state
                    entity_id: input_boolean.home_night_mode
                    state: "off"
                  - condition: state
                    entity_id: light.bedroom_nightlight
                    state: "off"
                then:
                  - action: light.turn_on
                    entity_id: light.bedroom_nightlight
                    data:
                      brightness: 255
                else:
                  - action: light.turn_off
                    entity_id: light.bedroom_nightlight
          - conditions:
              - "{{ command == 'hold' }}"
            sequence:
              # Allow to turn on bedroom lights and open cover
              - action: input_boolean.turn_off
                entity_id: input_boolean.bedroom_lights_and_cover_safety_switch
              # Open cover and make another actions
              - action: cover.open_cover
                entity_id: cover.bedroom
              - if:
                  - condition: state
                    entity_id: input_boolean.child_lock
                    state: "off"
                then:
                  - action: script.home_day_mode
        default: []

  ###############################################
  ## Aqara Cube Automations
  ###############################################
  - alias: Aqara Cube 1 Handler
    id: "aqara_cube_1_handler"
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: zha_event
        event_data:
          # Aqara Cube 1
          device_id: "48fad66663fc601ed1a63ac01e804fab"
    actions:
      - if:
          - condition: state
            entity_id: input_boolean.cube_1_control
            state: "on"
        then:
          - variables:
              command: "{{ trigger.event.data.command }}"
              flip_degrees: "{{ trigger.event.data.args.flip_degrees if trigger.event.data.args.flip_degrees is defined else 0 }}"
              relative_degrees: "{{ trigger.event.data.args.relative_degrees if trigger.event.data.args.relative_degrees is defined else 0 }}"
          - choose:
              - conditions:
                  - "{{ flip_degrees == 90 }}"
                sequence:
                  - action: light.toggle
                    entity_id: light.string_lights
              - conditions:
                  - "{{ flip_degrees == 180 }}"
                sequence:
                  - action: light.toggle
                    entity_id: light.floor_lamp
              - conditions:
                  - "{{ command == 'shake' }}"
                sequence:
                  - action: script.turn_on
                    entity_id: script.turn_off_all_lights
              - conditions:
                  - "{{ command == 'tap' }}"
                sequence:
                  - action: scene.turn_on
                    entity_id: scene.movies
              - conditions:
                  - "{{ command == 'slide' }}"
                sequence:
                  - action: light.turn_on
                    entity_id:
                      - light.gyver_lamp
                      - light.pc_backlight
              - conditions:
                  - "{{ command == 'rotate_left' or command == 'rotate_right' }}"
                sequence:
                  - action: light.turn_on
                    entity_id: light.floor_lamp
                    data_template:
                      brightness:
                        "{% set suggested = state_attr('light.floor_lamp', 'brightness')\
                        \ | int(0) + \n  relative_degrees | int(0) + 1\
                        \ %}\n{% if suggested > 0 %} {{ suggested }} {% else %} 1 {% endif %}\n"

  ###############################################
  ## Tradfri Switch Control
  ###############################################
  - alias: Tradfri Switch 1 Handler
    id: "tradfri_switch_1_handler"
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: zha_event
        event_data:
          # Tradfri Switch 1
          device_id: "a64c98fa9b0c36e96ebe42160fcf78b5"
    actions:
      - variables:
          command: "{{ trigger.event.data.command }}"
      - choose:
          - conditions:
              - "{{ command == 'on' }}"  # Single press UP
            sequence:
              - if:
                  - condition: state
                    entity_id: light.hall_edison_bulb
                    state: "off"
                then:
                  - action: light.turn_on
                    entity_id: light.hall_edison_bulb
                    data:
                      brightness: 255
                else:
                  - action: light.turn_on
                    entity_id: light.hall_lights
          - conditions:
              - "{{ command == 'off' }}"  # Single press DOWN
            sequence:
              - if:
                  - condition: state
                    entity_id: light.hall_lights
                    state: "on"
                then:
                  - action: light.turn_off
                    entity_id: light.hall_lights
                else:
                  - action: light.turn_off
                    entity_id: light.hall_edison_bulb
          - conditions:
              - "{{ command == 'move_with_on_off' }}"  # Hold UP
            sequence:
              - service: light.turn_on
                target:
                  area_id: hall
          - conditions:
              - "{{ command == 'move' }}"  # Hold DOWN
            sequence:
              - service: light.turn_off
                target:
                  area_id: hall

  ###############################################
  ## Ikea RODRET Dimmer
  ###############################################
  - alias: Rodret Dimmer 1 Handler
    id: "rodret_dimmer_1_handler"
    use_blueprint:
      path: damru/ikea-rodret_E2201_ZHA-Z2M_control-anything.yaml
      input:
        remote_device: 51724530dc1fcac3561d2fcb39f40048
        on_press_action:
          - action: switch.turn_on
            entity_id: switch.monolith_speakers
          - action: light.turn_on
            entity_id:
              - light.mi_desk_lamp
              - light.tv_lights
              - light.christmas_tree
        off_press_action:
          - action: switch.turn_off
            entity_id: switch.monolith_speakers
          - action: light.turn_off
            target:
              area_id: living_room
        on_hold_action:
          - action: light.turn_on
            entity_id: light.mi_desk_lamp
            data:
              brightness_step_pct: 4
        off_hold_action:
          - action: light.turn_on
            entity_id: light.mi_desk_lamp
            data:
              brightness_step_pct: -4
        helper_hold_delay: 200
        helper_max_loops: 20
