######################################################################
# File: zha_devices_actions.yaml                                     #
# Author: SenMorgan https://github.com/SenMorgan                     #
# Date: 2023-06-14                                                   #
#                                                                    #                                                                    #
# Copyright (c) 2023 Sen Morgan                                      #
#                                                                    #
# Note:                                                              #
# Device IDs are unique and could be found in:                       #
# Developer Tools → Events → Listen to events → "zha_event".         #
# After some action with device it must be loged there.              #
#                                                                    #
######################################################################

###############################################
## INPUT BOOLEANS
###############################################
input_boolean:
  cube_1_control:
    name: Cube Control
    icon: mdi:gesture-double-tap
  child_lock:
    name: Child Lock
    icon: mdi:lock
    initial: off

###############################################
## AUTOMATIONS
###############################################
automation:
  ###############################################
  ## Aqara Switch Automations
  ###############################################
  - alias: Aqara Switch 1 Handler
    id: "aqara_switch_1_handler"
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: zha_event
        event_data:
          # Aqara Switch 1
          device_id: "6559eaaf60c9624465f762290ff9e825"
    actions:
      - variables:
          command: "{{ trigger.event.data.command }}"
      - choose:
          - conditions:
              - "{{ command == 'single' }}"
            sequence:
              - if:
                  - condition: state
                    entity_id: input_boolean.child_lock
                    state: "off"
                then:
                  - action: scene.turn_on
                    entity_id: scene.good_night
                  - action: input_boolean.turn_on
                    entity_id:
                      - input_boolean.home_night_mode
                      - input_boolean.silent_mode
                  - action: script.turn_off_all_lights
                  - action: script.notify_if_some_window_is_opened_during_heating_season
                else:
                  - action: cover.toggle
                    entity_id: cover.bedroom
          - conditions:
              - "{{ command == 'double' }}"
            sequence:
              - action: light.toggle
                entity_id: light.bedroom_nightlight
                data:
                  brightness: 255
          - conditions:
              - "{{ command == 'triple' }}"
            sequence:
              - action: light.toggle
                entity_id: light.bedroom_nightlight
                data:
                  brightness: 1
          - conditions:
              - "{{ command == 'hold' }}"
            sequence:
              # Allow to turn on bedroom lights and open cover
              - action: input_boolean.turn_off
                entity_id: input_boolean.bedroom_lights_and_cover_safety_switch
              # Open cover and make another actions
              - action: cover.open_cover
                entity_id: cover.bedroom
              - if:
                  - condition: state
                    entity_id: input_boolean.child_lock
                    state: "off"
                then:
                  - action: scene.turn_on
                    entity_id: scene.good_morning
                  - action: input_boolean.turn_off
                    entity_id:
                      - input_boolean.home_night_mode
                      - input_boolean.silent_mode
        default: []

  ###############################################
  ## Aqara Cube Automations
  ###############################################
  - alias: Aqara Cube 1 Handler
    id: "aqara_cube_1_handler"
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: zha_event
        event_data:
          # Aqara Cube 1
          device_id: "48fad66663fc601ed1a63ac01e804fab"
    actions:
      - if:
          - condition: state
            entity_id: input_boolean.cube_1_control
            state: "on"
        then:
          - variables:
              command: "{{ trigger.event.data.command }}"
              flip_degrees: "{{ trigger.event.data.args.flip_degrees if trigger.event.data.args.flip_degrees is defined else 0 }}"
              relative_degrees: "{{ trigger.event.data.args.relative_degrees if trigger.event.data.args.relative_degrees is defined else 0 }}"
          - choose:
              - conditions:
                  - "{{ flip_degrees == 90 }}"
                sequence:
                  - action: light.toggle
                    entity_id: light.string_lights
              - conditions:
                  - "{{ flip_degrees == 180 }}"
                sequence:
                  - action: light.toggle
                    entity_id: light.floor_lamp
              - conditions:
                  - "{{ command == 'shake' }}"
                sequence:
                  - action: script.turn_on
                    entity_id: script.turn_off_all_lights
              - conditions:
                  - "{{ command == 'tap' }}"
                sequence:
                  - action: scene.turn_on
                    entity_id: scene.movies
              - conditions:
                  - "{{ command == 'slide' }}"
                sequence:
                  - action: light.turn_on
                    entity_id:
                      - light.gyver_lamp
                      - light.pc_backlight
              - conditions:
                  - "{{ command == 'rotate_left' or command == 'rotate_right' }}"
                sequence:
                  - action: light.turn_on
                    entity_id: light.mi_desk_lamp
                    data_template:
                      brightness:
                        "{% set suggested = state_attr('light.mi_desk_lamp', 'brightness')\
                        \ | int(0) + \n  relative_degrees | int(0) + 1\
                        \ %}\n{% if suggested > 0 %} {{ suggested }} {% else %} 1 {% endif %}\n"

  ###############################################
  ## Floorlamp Tradfri Switch Control
  ###############################################
  - alias: Tradfri Switch 1 Handler
    id: "tradfri_switch_1_handler"
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: zha_event
        event_data:
          # Tradfri Switch 1
          device_id: "a64c98fa9b0c36e96ebe42160fcf78b5"
    actions:
      - variables:
          command: "{{ trigger.event.data.command }}"
      - choose:
          - conditions:
              - "{{ command == 'on' }}"
            sequence:
              - action: input_boolean.turn_on
                entity_id: input_boolean.scooter_charger
          - conditions:
              - "{{ command == 'off' }}"
            sequence:
              - action: input_boolean.turn_off
                entity_id: input_boolean.scooter_charger

  ###############################################
  ## Ikea RODRET Dimmer Automations
  ###############################################
  - alias: Rodret Dimmer 1 Handler
    id: "rodret_dimmer_1_handler"
    use_blueprint:
      path: damru/ikea-rodret_E2201_ZHA-Z2M_control-anything.yaml
      input:
        remote_device: 51724530dc1fcac3561d2fcb39f40048
        on_press_action:
        - action: light.turn_on
          target:
            entity_id: light.living_room_nightlight
        - action: light.turn_on
          target:
            entity_id: light.bar_light
        off_press_action:
        - action: light.turn_off
          target:
            entity_id: light.living_room_nightlight
        - action: light.turn_off
          target:
            entity_id: light.bar_light
        on_hold_action:
        - action: light.turn_on
          data:
            brightness_step_pct: 4
          target:
            entity_id: light.living_room_nightlight
        off_hold_action:
        - action: light.turn_on
          data:
            brightness_step_pct: -4
          target:
            entity_id: light.living_room_nightlight
        helper_hold_delay: 200
        helper_max_loops: 20
